interface IInstruction {
  DEC: number;
  HEX: string;
  Mne: string;
  Description: string;
  OperandTypes: string;
  OperandSize: string;
  A: string;
  N: string;
  C: string;
  Z: string;
  Cycles: number;
}

const instructions: IInstruction[] = [
  {
    DEC: 0,
    HEX: "0x00",
    Mne: "NOP",
    Description: "No operation",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 16,
  },
  {
    DEC: 1,
    HEX: "0x01",
    Mne: "OUT",
    Description: "Output A to UART: UART = A",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "1",
    C: "0",
    Z: "0",
    Cycles: 2,
  },
  {
    DEC: 2,
    HEX: "0x02",
    Mne: "INT",
    Description: "Read UART input to A: A = UART",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 3,
  },
  {
    DEC: 3,
    HEX: "0x03",
    Mne: "INK",
    Description: "Read PS/2 input to A: A = PS2",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 3,
  },
  {
    DEC: 4,
    HEX: "0x04",
    Mne: "WIN",
    Description: "Wait for input",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 2,
  },
  {
    DEC: 5,
    HEX: "0x05",
    Mne: "SEC",
    Description: "Set carry flag (C=1)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "0",
    C: "1",
    Z: "0",
    Cycles: 3,
  },
  {
    DEC: 6,
    HEX: "0x06",
    Mne: "CLC",
    Description: "Clear carry flag (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "1",
    C: "0",
    Z: "0",
    Cycles: 3,
  },
  {
    DEC: 7,
    HEX: "0x07",
    Mne: "LL0",
    Description: "Logical left-shift A 0 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 8,
    HEX: "0x08",
    Mne: "LL1",
    Description: "Logical left-shift A 1 step (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 9,
    HEX: "0x09",
    Mne: "LL2",
    Description: "Logical left-shift A 2 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 10,
    HEX: "0x0a",
    Mne: "LL3",
    Description: "Logical left-shift A 3 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 11,
    HEX: "0x0b",
    Mne: "LL4",
    Description: "Logical left-shift A 4 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 12,
    HEX: "0x0c",
    Mne: "LL5",
    Description: "Logical left-shift A 5 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 13,
    HEX: "0x0d",
    Mne: "LL6",
    Description: "Logical left-shift A 6 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 14,
    HEX: "0x0e",
    Mne: "LL7",
    Description: "Logical left-shift A 7 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 15,
    HEX: "0x0f",
    Mne: "RL0",
    Description: "Rotate left A 0 steps via C (= RR9)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 16,
    HEX: "0x10",
    Mne: "RL1",
    Description: "Rotate left A 1 step via C (= RR8)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 17,
    HEX: "0x11",
    Mne: "RL2",
    Description: "Rotate left A 2 steps via C (= RR7)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 18,
    HEX: "0x12",
    Mne: "RL3",
    Description: "Rotate left A 3 steps via C (= RR6)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 19,
    HEX: "0x13",
    Mne: "RL4",
    Description: "Rotate left A 4 steps via C (= RR5)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 20,
    HEX: "0x14",
    Mne: "RL5",
    Description: "Rotate left A 5 steps via C (= RR4)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 21,
    HEX: "0x15",
    Mne: "RL6",
    Description: "Rotate left A 6 steps via C (= RR3)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 22,
    HEX: "0x16",
    Mne: "RL7",
    Description: "Rotate left A 7 steps via C (= RR2)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 23,
    HEX: "0x17",
    Mne: "RR1",
    Description: "Rotate right A 1 step via C (= RL8)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 24,
    HEX: "0x18",
    Mne: "LR0",
    Description: "Logical right-shift A 0 steps (C=0) (= RR0, RL9)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 25,
    HEX: "0x19",
    Mne: "LR1",
    Description: "Logical right-shift A 1 step (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 26,
    HEX: "0x1a",
    Mne: "LR2",
    Description: "Logical right-shift A 2 steps (C=0) §",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 15,
  },
  {
    DEC: 27,
    HEX: "0x1b",
    Mne: "LR3",
    Description: "Logical right-shift A 3 steps (C=0) §",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 15,
  },
  {
    DEC: 28,
    HEX: "0x1c",
    Mne: "LR4",
    Description: "Logical right-shift A 4 steps (C=0) §",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 15,
  },
  {
    DEC: 29,
    HEX: "0x1d",
    Mne: "LR5",
    Description: "Logical right-shift A 5 steps (C=0) §",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 15,
  },
  {
    DEC: 30,
    HEX: "0x1e",
    Mne: "LR6",
    Description: "Logical right-shift A 6 steps (C=0) §",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 13,
  },
  {
    DEC: 31,
    HEX: "0x1f",
    Mne: "LR7",
    Description: "Logical right-shift A 7 steps (C=0)",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 32,
    HEX: "0x20",
    Mne: "LLZ",
    Description: "Logical shift left *Z 1 step (C=0)",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 33,
    HEX: "0x21",
    Mne: "LLB",
    Description: "Logical shift byte left 1 step (C=0)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 34,
    HEX: "0x22",
    Mne: "LLV",
    Description: "Logical shift fast word left 1 step (C=0)",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 6,
  },
  {
    DEC: 35,
    HEX: "0x23",
    Mne: "LLW",
    Description: "Logical shift word left 1 step (C=0)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 8,
  },
  {
    DEC: 36,
    HEX: "0x24",
    Mne: "LLQ",
    Description: "Logical shift fast long left 1 step (C=0)",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 10,
  },
  {
    DEC: 37,
    HEX: "0x25",
    Mne: "LLL",
    Description: "Logical shift long left 1 step (C=0)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 12,
  },
  {
    DEC: 38,
    HEX: "0x26",
    Mne: "LRZ",
    Description: "Logical shift right zero-page byte 1 step (C=0)",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 11,
  },
  {
    DEC: 39,
    HEX: "0x27",
    Mne: "LRB",
    Description: "Logical shift right abs byte 1 step (C=0)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 13,
  },
  {
    DEC: 40,
    HEX: "0x28",
    Mne: "RLZ",
    Description: "Rotate left zero-page byte 1 step via C",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 41,
    HEX: "0x29",
    Mne: "RLB",
    Description: "Rotate left byte at abs addr 1 step via C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 42,
    HEX: "0x2a",
    Mne: "RLV",
    Description: "Rotate left zero-page word 1 step via C",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 6,
  },
  {
    DEC: 43,
    HEX: "0x2b",
    Mne: "RLW",
    Description: "Rotate left word at abs addr 1 step via C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 8,
  },
  {
    DEC: 44,
    HEX: "0x2c",
    Mne: "RLQ",
    Description: "Rotate left zero-page long 1 step via C",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 10,
  },
  {
    DEC: 45,
    HEX: "0x2d",
    Mne: "RLL",
    Description: "Rotate left abs long 1 step via C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 12,
  },
  {
    DEC: 46,
    HEX: "0x2e",
    Mne: "RRZ",
    Description: "Rotate right zero-page byte 1 step via C",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 11,
  },
  {
    DEC: 47,
    HEX: "0x2f",
    Mne: "RRB",
    Description: "Rotate right byte at abs addr 1 step via C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 13,
  },
  {
    DEC: 48,
    HEX: "0x30",
    Mne: "NOT",
    Description: "Bitwise NOT A: A = ~A",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 49,
    HEX: "0x31",
    Mne: "NOZ",
    Description: "Bitwise NOT *Z: *Z = ~(*Z)",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 5,
  },
  {
    DEC: 50,
    HEX: "0x32",
    Mne: "NOB",
    Description: "Bitwise NOT byte: *addr = ~(*addr)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 51,
    HEX: "0x33",
    Mne: "NOV",
    Description: "Bitwise NOT zero-page word: *V = ~(*V)",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 52,
    HEX: "0x34",
    Mne: "NOW",
    Description: "Bitwise NOT word at abs address",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 53,
    HEX: "0x35",
    Mne: "NOQ",
    Description: "Bitwise NOT zero-page long",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 11,
  },
  {
    DEC: 54,
    HEX: "0x36",
    Mne: "NOL",
    Description: "Bitwise NOT long at abs address",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 13,
  },
  {
    DEC: 55,
    HEX: "0x37",
    Mne: "NEG",
    Description: "Negate A: A = -A",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "Z",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 56,
    HEX: "0x38",
    Mne: "NEZ",
    Description: "Negate zero-page byte: *Z = -(*Z)",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "Z",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 57,
    HEX: "0x39",
    Mne: "NEB",
    Description: "Negate byte at abs address: *addr = -(*addr)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "Z",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 58,
    HEX: "0x3a",
    Mne: "NEV",
    Description: "Negate zero-page word (C = 1 only if word=0)",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "Z",
    Z: "M",
    Cycles: 7,
  },
  {
    DEC: 59,
    HEX: "0x3b",
    Mne: "NEW",
    Description: "Negate word at abs address (C = 1 only if word=0)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "Z",
    Z: "M",
    Cycles: 9,
  },
  {
    DEC: 60,
    HEX: "0x3c",
    Mne: "NEQ",
    Description: "Negate zero-page long (C = 1 only if long = 0)",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "Z",
    Z: "M",
    Cycles: 11,
  },
  {
    DEC: 61,
    HEX: "0x3d",
    Mne: "NEL",
    Description: "Negate long (C = 1 only if long = 0)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "Z",
    Z: "M",
    Cycles: 13,
  },
  {
    DEC: 62,
    HEX: "0x3e",
    Mne: "ANI",
    Description: "Bitwise AND: A = A & imm",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 63,
    HEX: "0x3f",
    Mne: "ANZ",
    Description: "Bitwise AND: A = A & *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 64,
    HEX: "0x40",
    Mne: "ANB",
    Description: "Bitwise AND: A = A & *addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 65,
    HEX: "0x41",
    Mne: "ANT",
    Description: "Bitwise AND: A = A & *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 66,
    HEX: "0x42",
    Mne: "ANR",
    Description: "Bitwise AND: A = A & *(*addr)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 67,
    HEX: "0x43",
    Mne: "AN.Z",
    Description: "Bitwise AND: *Z = *Z & A",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 68,
    HEX: "0x44",
    Mne: "AN.B",
    Description: "Bitwise AND: *addr = *addr & A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 69,
    HEX: "0x45",
    Mne: "ORI",
    Description: "Bitwise OR: A = A | imm",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 70,
    HEX: "0x46",
    Mne: "ORZ",
    Description: "Bitwise OR: A = A | *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 71,
    HEX: "0x47",
    Mne: "ORB",
    Description: "Bitwise OR: A = A | *addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 72,
    HEX: "0x48",
    Mne: "ORT",
    Description: "Bitwise OR: A = A | *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 73,
    HEX: "0x49",
    Mne: "ORR",
    Description: "Bitwise OR: A = A | *(*addr)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 74,
    HEX: "0x4a",
    Mne: "OR.Z",
    Description: "Bitwise OR: *Z = *Z | A",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 75,
    HEX: "0x4b",
    Mne: "OR.B",
    Description: "Bitwise OR: *addr = *addr | A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 76,
    HEX: "0x4c",
    Mne: "XRI",
    Description: "Bitwise XOR: A = A ^ imm §",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 77,
    HEX: "0x4d",
    Mne: "XRZ",
    Description: "Bitwise XOR: A = A ^ *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 10,
  },
  {
    DEC: 78,
    HEX: "0x4e",
    Mne: "XRB",
    Description: "Bitwise XOR: A = A ^ * addr §",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 12,
  },
  {
    DEC: 79,
    HEX: "0x4f",
    Mne: "XRT",
    Description: "Bitwise XOR: A = A ^ *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 13,
  },
  {
    DEC: 80,
    HEX: "0x50",
    Mne: "XRR",
    Description: "Bitwise XOR: A = A ^ *(*addr) §",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 15,
  },
  {
    DEC: 81,
    HEX: "0x51",
    Mne: "XR.Z",
    Description: "Bitwise XOR: *Z = *Z ^ A",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 82,
    HEX: "0x52",
    Mne: "XR.B",
    Description: "Bitwise XOR: *addr = *addr ^ A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 11,
  },
  {
    DEC: 83,
    HEX: "0x53",
    Mne: "FNE",
    Description: "Fast branch on non-zero",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 84,
    HEX: "0x54",
    Mne: "FEQ",
    Description: "Fast branch on zero",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 85,
    HEX: "0x55",
    Mne: "FCC",
    Description: "Fast branch on carry clear",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 86,
    HEX: "0x56",
    Mne: "FCS",
    Description: "Fast branch on carry set",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 87,
    HEX: "0x57",
    Mne: "FPL",
    Description: "Fast branch on plus",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 88,
    HEX: "0x58",
    Mne: "FMI",
    Description: "Fast branch on minus",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 89,
    HEX: "0x59",
    Mne: "FGT",
    Description: "Fast branch on greater",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 90,
    HEX: "0x5a",
    Mne: "FLE",
    Description: "Fast branch on less or equal",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 91,
    HEX: "0x5b",
    Mne: "FPA",
    Description: "Fast jump to lsb addr",
    OperandTypes: "addr lsb",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 92,
    HEX: "0x5c",
    Mne: "BNE",
    Description: "Branch on non-zero",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 93,
    HEX: "0x5d",
    Mne: "BEQ",
    Description: "Branch on zero",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 94,
    HEX: "0x5e",
    Mne: "BCC",
    Description: "Branch on carry clear",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 95,
    HEX: "0x5f",
    Mne: "BCS",
    Description: "Branch on carry set",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 96,
    HEX: "0x60",
    Mne: "BPL",
    Description: "Branch on plus",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 97,
    HEX: "0x61",
    Mne: "BMI",
    Description: "Branch on minus",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 98,
    HEX: "0x62",
    Mne: "BGT",
    Description: "Branch on greater",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 99,
    HEX: "0x63",
    Mne: "BLE",
    Description: "Branch on less or equal",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 100,
    HEX: "0x64",
    Mne: "JPA",
    Description: "Jump to abs address: PC = addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 101,
    HEX: "0x65",
    Mne: "JPR",
    Description: "Jump to rel address: PC = *addr",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 102,
    HEX: "0x66",
    Mne: "JAR",
    Description: "Jump A-indexed to rel address: PC = *(addr + A)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "-",
    N: "L",
    C: "L",
    Z: "L",
    Cycles: 7,
  },
  {
    DEC: 103,
    HEX: "0x67",
    Mne: "JPS",
    Description: "Jump to subroutine",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "?",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 11,
  },
  {
    DEC: 104,
    HEX: "0x68",
    Mne: "JAS",
    Description: "Jump to subroutine conserving A §",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 14,
  },
  {
    DEC: 105,
    HEX: "0x69",
    Mne: "RTS",
    Description: "Return from subroutine",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 10,
  },
  {
    DEC: 106,
    HEX: "0x6a",
    Mne: "PHS",
    Description: "Push A onto stack",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 8,
  },
  {
    DEC: 107,
    HEX: "0x6b",
    Mne: "PLS",
    Description: "Pull A from stack",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 108,
    HEX: "0x6c",
    Mne: "LDS",
    Description: "Load from stack: A = *(0xff00 + SP + off)",
    OperandTypes: "offset",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 109,
    HEX: "0x6d",
    Mne: "STS",
    Description: "Store on stack: *(0xff00 + SP + off) = A",
    OperandTypes: "offset",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 11,
  },
  {
    DEC: 110,
    HEX: "0x6e",
    Mne: "RDB",
    Description: "Read FLASH data from abs 3-byte address",
    OperandTypes: "addr,bnk",
    OperandSize: "2,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 8,
  },
  {
    DEC: 111,
    HEX: "0x6f",
    Mne: "RDR",
    Description: "Read FLASH data from rel 3-byte address",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 11,
  },
  {
    DEC: 112,
    HEX: "0x70",
    Mne: "RAP",
    Description: "Read A-indexed FLASH data: A = *(pg<<8 + A)",
    OperandTypes: "pg,bnk",
    OperandSize: "1,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 113,
    HEX: "0x71",
    Mne: "RZP",
    Description: "Read Z-indexed FLASH data: A = *(pg<<8 + *Z)",
    OperandTypes: "Z,pg,bnk",
    OperandSize: "1,1,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 114,
    HEX: "0x72",
    Mne: "WDB",
    Description: "Write FLASH data to abs 3-byte address §",
    OperandTypes: "addr,bnk",
    OperandSize: "2,1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 14,
  },
  {
    DEC: 115,
    HEX: "0x73",
    Mne: "WDR",
    Description: "Write FLASH data to rel 3-byte address §",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 16,
  },
  {
    DEC: 116,
    HEX: "0x74",
    Mne: "LDI",
    Description: "Load A immediate: A = imm",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
  {
    DEC: 117,
    HEX: "0x75",
    Mne: "LDZ",
    Description: "Load A from Z: A = *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 118,
    HEX: "0x76",
    Mne: "LDB",
    Description: "Load A from abs address: A = *addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 5,
  },
  {
    DEC: 119,
    HEX: "0x77",
    Mne: "LDT",
    Description: "Load A from rel address in zero page: A = *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 120,
    HEX: "0x78",
    Mne: "LDR",
    Description: "Load A from relative address: A = *(*addr)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 8,
  },
  {
    DEC: 121,
    HEX: "0x79",
    Mne: "LAP",
    Description: "Load A A-indexed from page: A = *(pg<<8 + A)",
    OperandTypes: "pg",
    OperandSize: "1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 122,
    HEX: "0x7a",
    Mne: "LAB",
    Description: "Load A A-indexed from addr: A = *(addr + A)",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "L",
    C: "L",
    Z: "L",
    Cycles: 5,
  },
  {
    DEC: 123,
    HEX: "0x7b",
    Mne: "LZP",
    Description: "Load A Z-indexed from page: A = *(pg<<8 + *Z)",
    OperandTypes: "Z,pg",
    OperandSize: "1,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 124,
    HEX: "0x7c",
    Mne: "LZB",
    Description: "Load A Z-indexed from addr: A = *(addr + *Z)",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "R",
    N: "L",
    C: "L",
    Z: "L",
    Cycles: 7,
  },
  {
    DEC: 125,
    HEX: "0x7d",
    Mne: "STZ",
    Description: "Store A to Z: *Z = A",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 3,
  },
  {
    DEC: 126,
    HEX: "0x7e",
    Mne: "STB",
    Description: "Store A to address: *addr = A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 5,
  },
  {
    DEC: 127,
    HEX: "0x7f",
    Mne: "STT",
    Description: "Store A at rel address in zero page: *(*Z) = A",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 128,
    HEX: "0x80",
    Mne: "STR",
    Description: "Store A at relative address: *(*addr) = A",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 8,
  },
  {
    DEC: 129,
    HEX: "0x81",
    Mne: "SZP",
    Description: "Store A Z-indexed to page: *(pg<<8 + *Z) = A",
    OperandTypes: "Z,pg",
    OperandSize: "1,1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 130,
    HEX: "0x82",
    Mne: "MIZ",
    Description: "Move imm byte to zero-page: *Z = imm",
    OperandTypes: "imm,Z",
    OperandSize: "1,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 131,
    HEX: "0x83",
    Mne: "MIB",
    Description: "Move imm byte to abs addr: *addr = imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 132,
    HEX: "0x84",
    Mne: "MIT",
    Description: "Move imm byte to rel zero-page addr: *(*T) = imm",
    OperandTypes: "imm,rel Z",
    OperandSize: "1,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 133,
    HEX: "0x85",
    Mne: "MIR",
    Description: "Move imm byte to rel addr: *(*addr) = imm",
    OperandTypes: "imm,rel",
    OperandSize: "1,2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 134,
    HEX: "0x86",
    Mne: "MIV",
    Description: "Move imm word to zero-page word: *V = imm",
    OperandTypes: "imm,V",
    OperandSize: "2,1",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 135,
    HEX: "0x87",
    Mne: "MIW",
    Description: "Move imm word to abs addr: *addr = imm",
    OperandTypes: "imm,addr",
    OperandSize: "2,2",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 13,
  },
  {
    DEC: 136,
    HEX: "0x88",
    Mne: "MZZ",
    Description: "Move zero-page byte to zero-page byte: *Z2 = *Z1",
    OperandTypes: "Z1,Z2",
    OperandSize: "1,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 5,
  },
  {
    DEC: 137,
    HEX: "0x89",
    Mne: "MZB",
    Description: "Move zero-page byte to abs addr: *addr = *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 138,
    HEX: "0x8a",
    Mne: "MBZ",
    Description: "Move byte at abs addr to zero-page: *Z = *addr",
    OperandTypes: "addr,Z",
    OperandSize: "2,1",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 139,
    HEX: "0x8b",
    Mne: "MBB",
    Description: "Move byte from abs adr1 to abs adr2: *adr2 = *adr1",
    OperandTypes: "adr1,adr2",
    OperandSize: "2,2",
    A: "R",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 140,
    HEX: "0x8c",
    Mne: "MVV",
    Description: "Move zero-page word to zero-page word: *V2 = *V1",
    OperandTypes: "V1,V2",
    OperandSize: "1,1",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 141,
    HEX: "0x8d",
    Mne: "MWV",
    Description: "Move word at abs addr to fast word: *V = *addr",
    OperandTypes: "addr,V",
    OperandSize: "2,1",
    A: "M",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 9,
  },
  {
    DEC: 142,
    HEX: "0x8e",
    Mne: "CLZ",
    Description: "Clear Z: *Z = 0x00",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 4,
  },
  {
    DEC: 143,
    HEX: "0x8f",
    Mne: "CLB",
    Description: "Clear byte at addr: *addr = 0x00",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 6,
  },
  {
    DEC: 144,
    HEX: "0x90",
    Mne: "CLV",
    Description: "Clear fast word: *V = 0x0000",
    OperandTypes: "V",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 5,
  },
  {
    DEC: 145,
    HEX: "0x91",
    Mne: "CLW",
    Description: "Clear word at addr: *addr = 0x0000",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "0",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 146,
    HEX: "0x92",
    Mne: "CLQ",
    Description: "Clear zero-page long: *Q = 0x00000000",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 7,
  },
  {
    DEC: 147,
    HEX: "0x93",
    Mne: "CLL",
    Description: "Clear long: *addr = 0x00000000",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "0",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 11,
  },
  {
    DEC: 148,
    HEX: "0x94",
    Mne: "INC",
    Description: "Increment A: A = A + 1",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 149,
    HEX: "0x95",
    Mne: "INZ",
    Description: "Increment zero-page byte: *Z = *Z + 1",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 150,
    HEX: "0x96",
    Mne: "INB",
    Description: "Increment byte at abs addr: *addr = *addr + 1",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 151,
    HEX: "0x97",
    Mne: "INV",
    Description: "Increment zero-page word: *V = *V + 0x0001",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 7,
  },
  {
    DEC: 152,
    HEX: "0x98",
    Mne: "INW",
    Description: "Increment word at abs addr: *addr = *addr + 0x0001",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 9,
  },
  {
    DEC: 153,
    HEX: "0x99",
    Mne: "INQ",
    Description: "Increment zero-page long: *Q = *Q + 0x00000001",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 6,
  },
  {
    DEC: 154,
    HEX: "0x9a",
    Mne: "INL",
    Description: "Increment long: *addr = *addr + 0x00000001",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 8686,
  },
  {
    DEC: 155,
    HEX: "0x9b",
    Mne: "DEC",
    Description: "Decrement A: A = A - 1",
    OperandTypes: "-",
    OperandSize: "-",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 156,
    HEX: "0x9c",
    Mne: "DEZ",
    Description: "Decrement *Z = *Z - 1",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 157,
    HEX: "0x9d",
    Mne: "DEB",
    Description: "Decrement byte: *addr = *addr - 1",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 158,
    HEX: "0x9e",
    Mne: "DEV",
    Description: "Decrement zero-page word: *V = *V - 0x0001",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 7,
  },
  {
    DEC: 159,
    HEX: "0x9f",
    Mne: "DEW",
    Description: "Decrement word at abs addr: *addr = *addr - 0x0001",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 9,
  },
  {
    DEC: 160,
    HEX: "0xa0",
    Mne: "DEQ",
    Description: "Decrement zero-page long: *Q = *Q - 0x00000001",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 6,
  },
  {
    DEC: 161,
    HEX: "0xa1",
    Mne: "DEL",
    Description: "Decrement long: *addr = *addr - 0x00000001",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 6,
  },
  {
    DEC: 162,
    HEX: "0xa2",
    Mne: "ADI",
    Description: "Add immediate to A: A = A + imm",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 163,
    HEX: "0xa3",
    Mne: "ADZ",
    Description: "Add zero-page byte to A: A = A + *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 164,
    HEX: "0xa4",
    Mne: "ADB",
    Description: "Add byte at addr to A: A = A + *addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 165,
    HEX: "0xa5",
    Mne: "ADT",
    Description: "Add byte at rel zero-page addr to A: A = A + *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 166,
    HEX: "0xa6",
    Mne: "ADR",
    Description: "Add byte at rel addr to A: A = A + *(*addr)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 167,
    HEX: "0xa7",
    Mne: "AD.Z",
    Description: "Add A to zero-page byte: *Z = *Z + A",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 168,
    HEX: "0xa8",
    Mne: "AD.B",
    Description: "Add A to byte at abs addr: *addr = *addr + A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 169,
    HEX: "0xa9",
    Mne: "AD.T",
    Description: "Add A to rel zero-page address: *(*Z) = *(*Z) + A",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 170,
    HEX: "0xaa",
    Mne: "AD.R",
    Description: "Add A to rel address: *(*addr) = *(*addr) + A",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 171,
    HEX: "0xab",
    Mne: "ADV",
    Description: "Add A to zero-page word: *V = *V + A",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 7,
  },
  {
    DEC: 172,
    HEX: "0xac",
    Mne: "ADW",
    Description: "Add A to word at abs addr: *addr = *addr + A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 9,
  },
  {
    DEC: 173,
    HEX: "0xad",
    Mne: "ADQ",
    Description: "Add A to zero-page long: *Q = *Q + A",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 5,
  },
  {
    DEC: 174,
    HEX: "0xae",
    Mne: "ADL",
    Description: "Add A to long: *addr = *addr + A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 7,
  },
  {
    DEC: 175,
    HEX: "0xaf",
    Mne: "AIZ",
    Description: "Add immediate to zero-page byte: *Z = *Z + imm",
    OperandTypes: "imm,Z",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 176,
    HEX: "0xb0",
    Mne: "AIB",
    Description: "Add imm to byte at abs addr: *addr = *addr + imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 177,
    HEX: "0xb1",
    Mne: "AIT",
    Description: "Add imm to byte at rel Z addr: *(*Z) = *(*Z) + imm",
    OperandTypes: "imm,rel Z",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 178,
    HEX: "0xb2",
    Mne: "AIR",
    Description: "Add imm to byte at rel addr: *(*adr) = *(*adr) + imm",
    OperandTypes: "imm,rel",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 179,
    HEX: "0xb3",
    Mne: "AIV",
    Description: "Add immediate byte to zero-page word: *V = *V + imm",
    OperandTypes: "imm,V",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 180,
    HEX: "0xb4",
    Mne: "AIW",
    Description: "Add imm byte to abs word: *addr = *addr + imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 10,
  },
  {
    DEC: 181,
    HEX: "0xb5",
    Mne: "AIQ",
    Description: "Add immediate byte to zero-page long: *Q = *Q + imm",
    OperandTypes: "imm,Q",
    OperandSize: "1,1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 6,
  },
  {
    DEC: 182,
    HEX: "0xb6",
    Mne: "AIL",
    Description: "Add immediate byte to long: *L = *L + imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 8,
  },
  {
    DEC: 183,
    HEX: "0xb7",
    Mne: "AZZ",
    Description: "Add zero-page byte to zero-page byte: *Z2 = *Z2 + *Z1",
    OperandTypes: "Z1,Z2",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 184,
    HEX: "0xb8",
    Mne: "AZB",
    Description: "Add zero-page to byte at abs addr: *addr = *addr + *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 185,
    HEX: "0xb9",
    Mne: "AZV",
    Description: "Add zero-page byte to zero-page word: *V = *V + *Z",
    OperandTypes: "Z,V",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 186,
    HEX: "0xba",
    Mne: "AZW",
    Description: "Add zero-page byte to word at addr: *addr = *addr + *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 11,
  },
  {
    DEC: 187,
    HEX: "0xbb",
    Mne: "AZQ",
    Description: "Add zero-page byte to zero-page long: *Q = *Q + *Z",
    OperandTypes: "Z,Q",
    OperandSize: "1,1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 7,
  },
  {
    DEC: 188,
    HEX: "0xbc",
    Mne: "AZL",
    Description: "Add zero-page byte to long: *L = *L + *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 9,
  },
  {
    DEC: 189,
    HEX: "0xbd",
    Mne: "ABZ",
    Description: "Add abs byte to zero-page byte: *Z = *Z + *addr",
    OperandTypes: "addr,Z",
    OperandSize: "2,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 190,
    HEX: "0xbe",
    Mne: "ABB",
    Description: "Add abs byte to byte: *adr2 = *adr2 + *adr1",
    OperandTypes: "adr1,adr2",
    OperandSize: "2,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 191,
    HEX: "0xbf",
    Mne: "ABV",
    Description: "Add abs byte to zero-page word: *V = *V + *addr",
    OperandTypes: "addr,V",
    OperandSize: "2,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 11,
  },
  {
    DEC: 192,
    HEX: "0xc0",
    Mne: "ABW",
    Description: "Add byte at ad1 to word at ad2: *ad2 = *ad2 + *ad1",
    OperandTypes: "ad1,ad2",
    OperandSize: "2,2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 13,
  },
  {
    DEC: 193,
    HEX: "0xc1",
    Mne: "ABQ",
    Description: "Add abs byte to zero-page long: *Q = *Q + *addr",
    OperandTypes: "addr,Q",
    OperandSize: "2,1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 9,
  },
  {
    DEC: 194,
    HEX: "0xc2",
    Mne: "AVV",
    Description: "Add zero-page word to zero-page word: *V2 = *V2 + *V1",
    OperandTypes: "V1,V2",
    OperandSize: "1,1",
    A: "M",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 14,
  },
  {
    DEC: 195,
    HEX: "0xc3",
    Mne: "SUI",
    Description: "Sub immediate from A: A = A - imm",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 196,
    HEX: "0xc4",
    Mne: "SUZ",
    Description: "Sub zero-page byte from A: A = A - *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 197,
    HEX: "0xc5",
    Mne: "SUB",
    Description: "Sub byte at addr from A: A = A - *addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 198,
    HEX: "0xc6",
    Mne: "SUT",
    Description: "Sub byte at rel zero-page addr from A: A = A - *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 199,
    HEX: "0xc7",
    Mne: "SUR",
    Description: "Sub byte at rel addr from A: A = A - *(*addr)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 200,
    HEX: "0xc8",
    Mne: "SU.Z",
    Description: "Sub A from zero-page byte: *Z = *Z - A",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 201,
    HEX: "0xc9",
    Mne: "SU.B",
    Description: "Sub A from byte at abs addr: *addr = *addr - A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 202,
    HEX: "0xca",
    Mne: "SU.T",
    Description: "Sub A from rel zero-page address: *(*Z) = *(*Z) - A",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 203,
    HEX: "0xcb",
    Mne: "SU.R",
    Description: "Sub A from byte at rel addr: *(*addr) = *(*addr) - A",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 204,
    HEX: "0xcc",
    Mne: "SUV",
    Description: "Sub A from zero-page word: *v = *V - A",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 8,
  },
  {
    DEC: 205,
    HEX: "0xcd",
    Mne: "SUW",
    Description: "Sub A from word at abs addr: *addr = *addr - A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 10,
  },
  {
    DEC: 206,
    HEX: "0xce",
    Mne: "SUQ",
    Description: "Sub A from zero-page long: *Q = *Q - A",
    OperandTypes: "Q",
    OperandSize: "1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 6,
  },
  {
    DEC: 207,
    HEX: "0xcf",
    Mne: "SUL",
    Description: "Sub A from long: *addr = *addr - A",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 8,
  },
  {
    DEC: 208,
    HEX: "0xd0",
    Mne: "SIZ",
    Description: "Sub immediate from zero-page byte: *Z = *Z - imm",
    OperandTypes: "imm,Z",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 209,
    HEX: "0xd1",
    Mne: "SIB",
    Description: "Sub imm from byte: *addr = *addr - imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 210,
    HEX: "0xd2",
    Mne: "SIT",
    Description: "Sub imm from byte at rel Z addr: *(*Z) = *(*Z) + imm",
    OperandTypes: "imm,rel Z",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 211,
    HEX: "0xd3",
    Mne: "SIR",
    Description: "Sub imm from byte at rel addr: *(*ad) = *(*ad) + imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 212,
    HEX: "0xd4",
    Mne: "SIV",
    Description: "Sub imm byte from zero-page word: *V = *V - imm",
    OperandTypes: "imm,V",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 213,
    HEX: "0xd5",
    Mne: "SIW",
    Description: "Sub imm byte from abs word: *addr = *addr - imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 10,
  },
  {
    DEC: 214,
    HEX: "0xd6",
    Mne: "SIQ",
    Description: "Sub imm byte from zero-page long Z: *Z = *Z - imm",
    OperandTypes: "imm,Q",
    OperandSize: "1,1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 6,
  },
  {
    DEC: 215,
    HEX: "0xd7",
    Mne: "SIL",
    Description: "Sub imm byte from long at abs address: *L = *L - imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 8,
  },
  {
    DEC: 216,
    HEX: "0xd8",
    Mne: "SZZ",
    Description: "Sub zero-page byte from Z byte: *Z2 = *Z2 - *Z1",
    OperandTypes: "Z1,Z2",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 217,
    HEX: "0xd9",
    Mne: "SZB",
    Description: "Sub zero-page byte from abs byte: *addr = *addr - *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 218,
    HEX: "0xda",
    Mne: "SZV",
    Description: "Sub zero-page byte from zero-page word: *V = *V - *Z",
    OperandTypes: "Z,V",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 219,
    HEX: "0xdb",
    Mne: "SZW",
    Description: "Sub zero-page byte from abs word: *addr = *addr - *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 11,
  },
  {
    DEC: 220,
    HEX: "0xdc",
    Mne: "SZQ",
    Description: "Sub zero-page byte from zero-page long: *Q = *Q - *Z",
    OperandTypes: "Z,Q",
    OperandSize: "1,1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 7,
  },
  {
    DEC: 221,
    HEX: "0xdd",
    Mne: "SZL",
    Description: "Sub zero-page byte from long: *L = *L - *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 9,
  },
  {
    DEC: 222,
    HEX: "0xde",
    Mne: "SBZ",
    Description: "Sub abs byte from zero-page byte: *Z = *Z - *addr",
    OperandTypes: "addr,Z",
    OperandSize: "2,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 223,
    HEX: "0xdf",
    Mne: "SBB",
    Description: "Sub abs byte from byte: *adr2 = *adr2 - *adr1",
    OperandTypes: "adr1,adr2",
    OperandSize: "2,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 224,
    HEX: "0xe0",
    Mne: "SBV",
    Description: "Sub abs byte from zero-page word: *V = *V - *addr",
    OperandTypes: "addr,V",
    OperandSize: "2,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 11,
  },
  {
    DEC: 225,
    HEX: "0xe1",
    Mne: "SBW",
    Description: "Sub abs byte from word at adr2: *adr2 = *adr2 - *adr1",
    OperandTypes: "adr1,adr2",
    OperandSize: "2,2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 13,
  },
  {
    DEC: 226,
    HEX: "0xe2",
    Mne: "SBQ",
    Description: "Sub abs byte from zero-page long: *Q = *Q - *addr",
    OperandTypes: "addr,Q",
    OperandSize: "2,1",
    A: "?",
    N: "?",
    C: "?",
    Z: "?",
    Cycles: 9,
  },
  {
    DEC: 227,
    HEX: "0xe3",
    Mne: "SVV",
    Description: "Sub zero-page word from word: *V2 = *V2 - *V1",
    OperandTypes: "V1,V2",
    OperandSize: "1,1",
    A: "M",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 14,
  },
  {
    DEC: 228,
    HEX: "0xe4",
    Mne: "CPI",
    Description: "Compare immediate value to A: eval A - imm",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "-",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 229,
    HEX: "0xe5",
    Mne: "CPZ",
    Description: "Compare zero-page byte to A: eval A - *Z",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "-",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 230,
    HEX: "0xe6",
    Mne: "CPB",
    Description: "Compare byte at addr to A: eval A - *addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "-",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 231,
    HEX: "0xe7",
    Mne: "CPT",
    Description: "Compare byte at rel Z to A: eval A - *(*Z)",
    OperandTypes: "rel Z",
    OperandSize: "1",
    A: "-",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 232,
    HEX: "0xe8",
    Mne: "CPR",
    Description: "Compare rel byte to A: eval A - *(*addr)",
    OperandTypes: "rel addr",
    OperandSize: "2",
    A: "-",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 9,
  },
  {
    DEC: 233,
    HEX: "0xe9",
    Mne: "CIZ",
    Description: "Compare imm to zero-page byte: A = *Z - imm",
    OperandTypes: "imm,Z",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 234,
    HEX: "0xea",
    Mne: "CIB",
    Description: "Compare imm to byte at abs addr: A = *addr - imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 235,
    HEX: "0xeb",
    Mne: "CIT",
    Description: "Compare imm to byte at rel Z: A = *(*Z) - imm",
    OperandTypes: "imm,rel Z",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 236,
    HEX: "0xec",
    Mne: "CIR",
    Description: "Compare imm to byte at rel addr: A = *(*addr) - imm",
    OperandTypes: "imm,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 237,
    HEX: "0xed",
    Mne: "CZZ",
    Description: "Compare zero-page byte to byte: A = *Z2 - *Z1",
    OperandTypes: "Z1,Z2",
    OperandSize: "1,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 238,
    HEX: "0xee",
    Mne: "CZB",
    Description: "Compare zero-page byte to byte: A = *addr - *Z",
    OperandTypes: "Z,addr",
    OperandSize: "1,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 239,
    HEX: "0xef",
    Mne: "CBZ",
    Description: "Compare abs byte to zero-page byte: A = *addr - *Z",
    OperandTypes: "addr,Z",
    OperandSize: "2,1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 8,
  },
  {
    DEC: 240,
    HEX: "0xf0",
    Mne: "CBB",
    Description: "Compare abs byte to byte: A = *adr2 - *adr1",
    OperandTypes: "adr1,adr2",
    OperandSize: "2,2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 10,
  },
  {
    DEC: 241,
    HEX: "0xf1",
    Mne: "ACI",
    Description: "Add immediate value to A with C: A = A + imm + C",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 242,
    HEX: "0xf2",
    Mne: "ACZ",
    Description: "Add zero-page byte with C to A: A = A + *Z + C",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 243,
    HEX: "0xf3",
    Mne: "ACB",
    Description: "Add byte at addr with C to A: A = A + *addr + C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 244,
    HEX: "0xf4",
    Mne: "AC.Z",
    Description: "Add A with C to zero-page byte: *Z = *Z + A + C",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 245,
    HEX: "0xf5",
    Mne: "AC.B",
    Description: "Add A with C to byte at addr: *addr = *addr + A + C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 246,
    HEX: "0xf6",
    Mne: "ACV",
    Description: "Add A with C to zero-page word",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 7,
  },
  {
    DEC: 247,
    HEX: "0xf7",
    Mne: "ACW",
    Description: "Add A with C to word at ads addr: *adr = *adr + A + C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 9,
  },
  {
    DEC: 248,
    HEX: "0xf8",
    Mne: "SCI",
    Description: "Sub imm value from A with C: A = A - imm - 1 + C",
    OperandTypes: "imm",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 3,
  },
  {
    DEC: 249,
    HEX: "0xf9",
    Mne: "SCZ",
    Description: "Sub zero-page byte with C from A: A = A - *Z - 1 + C",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 4,
  },
  {
    DEC: 250,
    HEX: "0xfa",
    Mne: "SCB",
    Description: "Sub byte at addr from A with C: A = A - *addr - 1 + C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 6,
  },
  {
    DEC: 251,
    HEX: "0xfb",
    Mne: "SC.Z",
    Description: "Sub A with C from zero-page byte: *Z = *Z - A - 1 + C",
    OperandTypes: "Z",
    OperandSize: "1",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 5,
  },
  {
    DEC: 252,
    HEX: "0xfc",
    Mne: "SC.B",
    Description: "Sub A with C from byte: *addr = *addr - A - 1 + C",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "R",
    N: "R",
    C: "R",
    Z: "R",
    Cycles: 7,
  },
  {
    DEC: 253,
    HEX: "0xfd",
    Mne: "SCV",
    Description: "Sub A with C from zero-page word",
    OperandTypes: "V",
    OperandSize: "1",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 8,
  },
  {
    DEC: 254,
    HEX: "0xfe",
    Mne: "SCW",
    Description: "Sub A with C from word at abs addr",
    OperandTypes: "addr",
    OperandSize: "2",
    A: "M",
    N: "M",
    C: "M",
    Z: "M",
    Cycles: 10,
  },
  {
    DEC: 255,
    HEX: "0xff",
    Mne: "-",
    Description: "Set bank register to 0xff (FLASH OFF) after boot-up",
    OperandTypes: "-",
    OperandSize: "-",
    A: "-",
    N: "-",
    C: "-",
    Z: "-",
    Cycles: 2,
  },
];

const getOperandInfo = (i: IInstruction) => {
  if (i.OperandTypes === "-") {
    return [];
  }

  const types = i.OperandTypes.split(",").map((op) => op.trim());
  const sizes = i.OperandSize.split(",").map((size) => parseInt(size));

  if (types.length !== sizes.length) {
    throw new Error(`Mismatched operand types and sizes for instruction ${i.Mne}`);
  }

  let pcOffset = 1;
  const operandInfo: { type: string; size: number; pcOffset: number }[] = [];

  types.forEach((operandType, index) => {
    const size = sizes[index];
    operandInfo.push({
      type: operandType,
      size: size,
      pcOffset: pcOffset,
    });
    pcOffset += size;
  });
  return operandInfo;
};

export const instructionInfo = instructions.map((i) => ({
  hex: i.HEX,
  menmonic: i.Mne,
  operands: getOperandInfo(i),
  description: i.Description,
  cycles: i.Cycles,
  changes: [i.A, i.N, i.C, i.Z],
  dec: i.DEC,
}));
