#org 0x2000     MIB 0xfe,0xffff                               ; initialize stack

loop2:          JPS _Random CPI 200 FCS loop2                 ; 
                  LL1 STZ 0x80 LDI 0 RL1 STZ 0x81                   
       ; get random number < 200, double it and store in 0x80
       ; set z flag and store 0 at 0x81

                  JPS _Random ANI 1 OR.Z 0x80
        ; get random 0 or 1
        ; add it to 0x80 - 0x80 is now a random number between 0-400




  loop70:       JPS _Random CPI 240 FCS loop70 STZ 0x82

      ; 0x82 now a random y pos between 0-240

                JPS _SetPixel
                JPS _ReadInput CPI 0 FEQ loop2
                  JPS _Clear

                  ; set cusor to bottom left
                  JPA _Prompt                                 ; and exit
#mute

#org 0x0080

sx:             0xffff                                        ; sprite engine
sy:             0xff
sh:             0xff                                          ; number of sprite lines to process
sptr:           0xffff
dptr:           0xffff                                        ; sprite data pointer
vadr:           0xffff                                        ; vram address to write to
sbuf:           0, 0, 0, 0xff                                 ; generate the shifted sprite pattern
shift:          0xff                                          ; number of pixels to shift
mask:           0xff, 0, 0, 0xff                              ; generate the shifted delete pattern

#org 0x430c ViewPort:

#mute ; MinOS API definitions generated by 'asm os.asm -s_'

#org 0xf000 _Start:
#org 0xf003 _Prompt:
#org 0xf006 _MemMove:
#org 0xf009 _Random:
#org 0xf00c _ScanPS2:
#org 0xf00f _ResetPS2:
#org 0xf012 _ReadInput:
#org 0xf015 _WaitInput:
#org 0xf018 _ReadLine:
#org 0xf01b _SkipSpace:
#org 0xf01e _ReadHex:
#org 0xf021 _SerialWait:
#org 0xf024 _SerialPrint:
#org 0xf027 _FindFile:
#org 0xf02a _LoadFile:
#org 0xf02d _SaveFile:
#org 0xf030 _ClearVRAM:
#org 0xf033 _Clear:
#org 0xf036 _ClearRow:
#org 0xf039 _ScrollUp:
#org 0xf03c _ScrollDn:
#org 0xf03f _Char:
#org 0xf042 _PrintChar:
#org 0xf045 _Print:
#org 0xf048 _PrintPtr:
#org 0xf04b _PrintHex:
#org 0xf04e _SetPixel:
#org 0xf051 _Line:
#org 0xf054 _Rect:
#org 0x00c0 _XPos:
#org 0x00c1 _YPos:
#org 0x00c2 _RandomState: 0,1,2,3
#org 0x00c6 _ReadNum:
#org 0x00c9 _ReadPtr:
#org 0x00cd _ReadBuffer:
