const mne = [
  "NOP",
  "OUT",
  "INT",
  "INK",
  "WIN",
  "LL0",
  "LL1",
  "LL2",
  "LL3",
  "LL4",
  "LL5",
  "LL6",
  "LL7",
  "RL0",
  "RL1",
  "RL2",
  "RL3",
  "RL4",
  "RL5",
  "RL6",
  "RL7",
  "RR1",
  "LR0",
  "LR1",
  "LR2",
  "LR3",
  "LR4",
  "LR5",
  "LR6",
  "LR7",
  "LLZ",
  "LLB",
  "LLV",
  "LLW",
  "LLQ",
  "LLL",
  "LRZ",
  "LRB",
  "RLZ",
  "RLB",
  "RLV",
  "RLW",
  "RLQ",
  "RLL",
  "RRZ",
  "RRB",
  "NOT",
  "NOZ",
  "NOB",
  "NOV",
  "NOW",
  "NOQ",
  "NEG",
  "NEZ",
  "NEB",
  "NEV",
  "NEW",
  "NEQ",
  "ANI",
  "ANZ",
  "ANB",
  "ANT",
  "ANR",
  "AN.Z",
  "AN.B",
  "AN.T",
  "AN.R",
  "ORI",
  "ORZ",
  "ORB",
  "ORT",
  "ORR",
  "OR.Z",
  "OR.B",
  "OR.T",
  "OR.R",
  "XRI",
  "XRZ",
  "XRB",
  "XRT",
  "XRR",
  "XR.Z",
  "XR.B",
  "XR.T",
  "XR.R",
  "FNE",
  "FEQ",
  "FCC",
  "FCS",
  "FPL",
  "FMI",
  "FGT",
  "FLE",
  "FPA",
  "BNE",
  "BEQ",
  "BCC",
  "BCS",
  "BPL",
  "BMI",
  "BGT",
  "BLE",
  "JPA",
  "JPR",
  "JAR",
  "JPS",
  "JAS",
  "RTS",
  "PHS",
  "PLS",
  "LDS",
  "SDS",
  "RDB",
  "RDR",
  "RAP",
  "RZP",
  "WDB",
  "WDR",
  "LDI",
  "LDZ",
  "LDB",
  "LDT",
  "LDR",
  "LAP",
  "LAB",
  "LZP",
  "LZB",
  "SDZ",
  "SDB",
  "SDT",
  "SDR",
  "SZP",
  "MIZ",
  "MIB",
  "MIT",
  "MIR",
  "MIV",
  "MIW",
  "MZZ",
  "MZB",
  "MZT",
  "MZR",
  "MBZ",
  "MBB",
  "MBT",
  "MBR",
  "MTZ",
  "MTB",
  "MTT",
  "MTR",
  "MRZ",
  "MRB",
  "MRT",
  "MRR",
  "MVV",
  "MWV",
  "CLD",
  "CLZ",
  "CLB",
  "CLV",
  "CLW",
  "CLQ",
  "CLL",
  "CL5",
  "INC",
  "INZ",
  "INB",
  "INV",
  "INW",
  "INQ",
  "DEC",
  "DEZ",
  "DEB",
  "DEV",
  "DEW",
  "DEQ",
  "ADI",
  "ADZ",
  "ADB",
  "ADT",
  "ADR",
  "AD.Z",
  "AD.B",
  "AD.T",
  "AD.R",
  "ADV",
  "ADW",
  "ADQ",
  "AIZ",
  "AIB",
  "AIT",
  "AIR",
  "AIV",
  "AIW",
  "AIQ",
  "AZZ",
  "AZT",
  "AZV",
  "AZQ",
  "ABB",
  "ABW",
  "ATZ",
  "ATT",
  "AVV",
  "SUI",
  "SUZ",
  "SUB",
  "SUT",
  "SUR",
  "SU.Z",
  "SU.B",
  "SU.T",
  "SU.R",
  "SUV",
  "SUW",
  "SUQ",
  "SIZ",
  "SIB",
  "SIT",
  "SIR",
  "SIV",
  "SIW",
  "SIQ",
  "SZZ",
  "SZT",
  "SZV",
  "SZQ",
  "SBB",
  "SBW",
  "STZ",
  "STT",
  "SVV",
  "CPI",
  "CPZ",
  "CPB",
  "CPT",
  "CPR",
  "CIZ",
  "CIB",
  "CIT",
  "CIR",
  "CIV",
  "CIW",
  "CZZ",
  "CZT",
  "CBB",
  "CTZ",
  "CTT",
  "CVV",
  "ACI",
  "ACZ",
  "AC.Z",
  "SCI",
  "SCZ",
  "SC.Z",
  "-",
];

const helps = [
  "No operation",
  "Output A to UART: UART = A",
  "Read UART input to A: A = UART",
  "Read PS/2 input to A: A = PS2",
  "Wait for any input (UART or PS/2)",
  "Logical left-shift A 0 steps (C=0)",
  "Logical left-shift A 1 step (C=0)",
  "Logical left-shift A 2 steps (C=0)",
  "Logical left-shift A 3 steps (C=0)",
  "Logical left-shift A 4 steps (C=0)",
  "Logical left-shift A 5 steps (C=0)",
  "Logical left-shift A 6 steps (C=0)",
  "Logical left-shift A 7 steps (C=0)",
  "Rotate left A 0 steps via C (= RR9)",
  "Rotate left A 1 step via C (= RR8)",
  "Rotate left A 2 steps via C (= RR7)",
  "Rotate left A 3 steps via C (= RR6)",
  "Rotate left A 4 steps via C (= RR5)",
  "Rotate left A 5 steps via C (= RR4)",
  "Rotate left A 6 steps via C (= RR3)",
  "Rotate left A 7 steps via C (= RR2)",
  "Rotate right A 1 step via C (= RL8)",
  "Logical right-shift A 0 steps (C=0) (= RR0, RL9)",
  "Logical right-shift A 1 step (C=0)",
  "Logical right-shift A 2 steps (C=0) §",
  "Logical right-shift A 3 steps (C=0) §",
  "Logical right-shift A 4 steps (C=0) §",
  "Logical right-shift A 5 steps (C=0) §",
  "Logical right-shift A 6 steps (C=0) §",
  "Logical right-shift A 7 steps (C=0)",
  "Logical shift left *Z 1 step (C=0)",
  "Logical shift byte left 1 step (C=0)",
  "Logical shift fast word left 1 step (C=0)",
  "Logical shift word left 1 step (C=0)",
  "Logical shift fast long left 1 step (C=0)",
  "Logical shift long left 1 step (C=0)",
  "Logical shift right zero-page byte 1 step (C=0)",
  "Logical shift right abs byte 1 step (C=0)",
  "Rotate left zero-page byte 1 step via C",
  "Rotate left byte at addr 1 step via C",
  "Rotate left zero-page word 1 step via C",
  "Rotate left word at addr 1 step via C",
  "Rotate left zero-page long 1 step via C",
  "Rotate left abs long 1 step via C",
  "Rotate right zero-page byte 1 step via C",
  "Rotate right byte at addr 1 step via C",
  "Bitwise NOT A: A = ~A",
  "Bitwise NOT *Z: *Z = ~*Z",
  "Bitwise NOT byte: *addr = ~*addr",
  "Bitwise NOT zero-page word: *V = ~(*V)",
  "Bitwise NOT word at address",
  "Bitwise NOT zero-page long",
  "Negate A: A = -A",
  "Negate zero-page byte: *Z = -*Z",
  "Negate byte at address: *addr = -*addr",
  "Negate zero-page word (C = 1 only if word = 0)",
  "Negate word at address (C = 1 only if word = 0)",
  "Negate zero-page long (C = 1 only if long = 0)",
  "Bitwise AND: A = A & imm",
  "Bitwise AND: A = A & *Z",
  "Bitwise AND: A = A & *addr",
  "Bitwise AND: A = A & **Z",
  "Bitwise AND: A = A & **addr",
  "Bitwise AND: *Z = *Z & A",
  "Bitwise AND: *addr = *addr & A",
  "Bitwise AND: **Z = A & **Z",
  "Bitwise AND: **addr = A & **addr",
  "Bitwise OR: A = A | imm",
  "Bitwise OR: A = A | *Z",
  "Bitwise OR: A = A | *addr",
  "Bitwise OR: A = A | **Z",
  "Bitwise OR: A = A | **addr",
  "Bitwise OR: *Z = *Z | A",
  "Bitwise OR: *addr = *addr | A",
  "Bitwise OR: **Z = A | **Z",
  "Bitwise OR: **addr = A | **addr",
  "Bitwise XOR: A = A ^ imm §",
  "Bitwise XOR: A = A ^ *Z",
  "Bitwise XOR: A = A ^ * addr §",
  "Bitwise XOR: A = A ^ **Z",
  "Bitwise XOR: A = A ^ **addr §",
  "Bitwise XOR: *Z = *Z ^ A",
  "Bitwise XOR: *addr = *addr ^ A",
  "Bitwise XOR: **Z = A ^ **Z",
  "Bitwise XOR: **addr = A ^ **addr §",
  "Fast branch on non-zero",
  "Fast branch on zero",
  "Fast branch on carry clear",
  "Fast branch on carry set",
  "Fast branch on plus",
  "Fast branch on minus",
  "Fast branch on greater",
  "Fast branch on less or equal",
  "Fast jump to lsb addr",
  "Branch on non-zero",
  "Branch on zero",
  "Branch on carry clear",
  "Branch on carry set",
  "Branch on plus",
  "Branch on minus",
  "Branch on greater",
  "Branch on less or equal",
  "Jump to address: PC = addr",
  "Jump to rel address: PC = *addr",
  "Jump A-indexed to rel address: PC = *(addr + A)",
  "Jump to subroutine",
  "Jump to subroutine conserving A §",
  "Return from subroutine",
  "Push A onto stack",
  "Pull A from stack",
  "Load from stack: A = *(0xff00 + SP + off)",
  "Store on stack: *(0xff00 + SP + off) = A",
  "Read FLASH data from abs 3-byte address",
  "Read FLASH data from rel 3-byte address",
  "Read A-indexed FLASH data: A = *(page<<8 + A)",
  "Read Z-indexed FLASH data: A = *(page<<8 + *Z)",
  "Write FLASH data to abs 3-byte address §",
  "Write FLASH data to rel 3-byte address §",
  "Load A immediate: A = imm",
  "Load A from Z: A = *Z",
  "Load A from address: A = *addr",
  "Load A from rel address in zero page: A = **Z",
  "Load A from relative address: A = **addr",
  "Load A A-indexed from page: A = *(page<<8 + A)",
  "Load A A-indexed from addr: A = *(addr + A)",
  "Load A Z-indexed from page: A = *(page<<8 + *Z)",
  "Load A Z-indexed from addr: A = *(addr + *Z)",
  "Store A to Z: *Z = A",
  "Store A to address: *addr = A",
  "Store A at rel address in zero page: **Z = A",
  "Store A at relative address: **addr = A",
  "Store A Z-indexed to page: *(page<<8 + *Z) = A",
  "Move imm byte to zero-page: *Z = imm",
  "Move imm byte to addr: *addr = imm",
  "Move imm byte to rel zero-page addr: *(*T) = imm",
  "Move imm byte to rel addr: **addr = imm",
  "Move imm word to zero-page word: *V = imm",
  "Move imm word to addr: *addr = imm",
  "Move byte at ZP addr to zero-page addr: *Z2 = *Z1",
  "Move byte at ZP addr to addr: *addr = *Z",
  "Move byte at ZP addr to rel ZP addr: **Z2 = *Z1",
  "Move byte at ZP addr to rel addr: **addr = *Z1",
  "Move byte at addr to zero-page: *Z = *addr",
  "Move byte at adr1 to adr2: *adr2 = *adr1",
  "Move byte at addr to rel ZP addr: **Z = *addr",
  "Move byte at adr1 to rel adr2: **adr2 = *adr1",
  "Move byte at rel ZP addr to ZP addr: *Z2 = **Z1",
  "Move byte at rel ZP addr to addr: *addr = **Z",
  "Move byte at rel ZP adr to rel ZP adr: **Z2 = **Z1",
  "Move byte at rel ZP addr to rel addr: **addr = **Z",
  "Move byte at rel addr to ZP addr: *Z = **addr",
  "Move byte at rel adr1 to adr2: *adr2 = **adr1",
  "Move byte at rel addr to rel ZP addr: **Z = **addr",
  "Move byte at rel adr1 to rel adr2: **adr2 = **adr1",
  "Move word at ZP addr to word at ZP addr: *V2 = *V1",
  "Move word at addr to word at ZP addr: *V = *addr",
  "Clear A: A = 0x00",
  "Clear byte at zero-page addr: *Z = 0x00",
  "Clear byte at addr: *addr = 0x00",
  "Clear word at zero-page addr: *V = 0x0000",
  "Clear word at addr: *addr = 0x0000",
  "Clear long at zero-page addr: *Q = 0x00000000",
  "Clear long at addr: *addr = 0x00000000",
  "Clear data at rel ZP: **Z = 0x0000000000 and *Z += 5",
  "Increment A: A = A + 1",
  "Increment zero-page byte: *Z = *Z + 1",
  "Increment byte at addr: *addr = *addr + 1",
  "Increment zero-page word: *V = *V + 0x0001",
  "Increment word at addr: *addr = *addr + 0x0001",
  "Increment zero-page long: *Q = *Q + 0x00000001",
  "Decrement A: A = A - 1",
  "Decrement *Z = *Z - 1",
  "Decrement byte: *addr = *addr - 1",
  "Decrement zero-page word: *V = *V - 0x0001",
  "Decrement word at addr: *addr = *addr - 0x0001",
  "Decrement zero-page long: *Q = *Q - 0x00000001",
  "Add immediate to A: A = A + imm",
  "Add zero-page byte to A: A = A + *Z",
  "Add byte at addr to A: A = A + *addr",
  "Add byte at rel zero-page addr to A: A = A + **Z",
  "Add byte at rel addr to A: A = A + **addr",
  "Add A to zero-page byte: *Z = *Z + A",
  "Add A to byte at addr: *addr = *addr + A",
  "Add A to rel zero-page address: **Z = **Z + A",
  "Add A to rel address: **addr = **addr + A",
  "Add A to zero-page word: *V = *V + A",
  "Add A to word at addr: *addr = *addr + A",
  "Add A to zero-page long: *Q = *Q + A",
  "Add imm byte to zero-page byte: *Z = *Z + imm",
  "Add imm to byte at addr: *addr = *addr + imm",
  "Add imm to byte at rel Z addr: **Z = **Z + imm",
  "Add imm to byte at rel adr: *(*adr) = *(*adr) + imm",
  "Add imm byte to zero-page word: *V = *V + imm",
  "Add imm byte to abs word: *addr = *addr + imm",
  "Add imm byte to zero-page long: *Q = *Q + imm",
  "Add zero-page byte to zero-page byte: *Z2 = *Z2 + *Z1",
  "Add ZP byte to rel ZP address: **Z2 = **Z2 + *Z1",
  "Add zero-page byte to zero-page word: *V = *V + *Z",
  "Add zero-page byte to zero-page long: *Q = *Q + *Z",
  "Add abs byte to byte: *adr2 = *adr2 + *adr1",
  "Add byte at ad1 to word at ad2: *ad2 = *ad2 + *ad1",
  "Add byte at rel ZP addr to ZP byte: *Z2 = *Z2 + **Z1",
  "Add byte at rel ZP to rel ZP: **Z2 = **Z2 + **Z1",
  "Add zero-page word to zero-page word: *V2 = *V2 + *V1",
  "Sub immediate from A: A = A - imm",
  "Sub zero-page byte from A: A = A - *Z",
  "Sub byte at addr from A: A = A - *addr",
  "Sub byte at rel zero-page addr from A: A = A - **Z",
  "Sub byte at rel addr from A: A = A - **addr",
  "Sub A from zero-page byte: *Z = *Z - A",
  "Sub A from byte at addr: *addr = *addr - A",
  "Sub A from rel zero-page address: **Z = **Z - A",
  "Sub A from byte at rel addr: **addr = **addr - A",
  "Sub A from zero-page word: *v = *V - A",
  "Sub A from word at addr: *addr = *addr - A",
  "Sub A from zero-page long: *Q = *Q - A",
  "Sub immediate from zero-page byte: *Z = *Z - imm",
  "Sub imm from byte: *addr = *addr - imm",
  "Sub imm from byte at rel Z addr: **Z = **Z + imm",
  "Sub imm from byte at rel addr: *(*ad) = *(*ad) + imm",
  "Sub imm byte from zero-page word: *V = *V - imm",
  "Sub imm byte from abs word: *addr = *addr - imm",
  "Sub imm byte from zero-page long Z: *Z = *Z - imm",
  "Sub zero-page byte from Z byte: *Z2 = *Z2 - *Z1",
  "Sub ZP byte from rel ZP address: **Z2 = **Z2 + *Z1",
  "Sub zero-page byte from zero-page word: *V = *V - *Z",
  "Sub zero-page byte from zero-page long: *Q = *Q - *Z",
  "Sub abs byte from byte: *adr2 = *adr2 - *adr1",
  "Sub abs byte from word at adr2: *adr2 = *adr2 - *adr1",
  "Sub byte at rel ZP addr from ZP byte: *Z2 = *Z2 - **Z1",
  "Sub byte at rel ZP from rel ZP: **Z2 = **Z2 - **Z1",
  "Sub zero-page word from word: *V2 = *V2 - *V1",
  "Compare imm byte to A: eval A - imm",
  "Compare byte in zero-page to A: eval A - *Z",
  "Compare byte at addr to A: eval A - *addr",
  "Compare byte at rel Z to A: eval A - **Z",
  "Compare byte at rel addr to A: eval A - **addr",
  "Compare imm byte to zero-page byte: LDZ Z CPI ..",
  "Compare imm byte to byte at addr: LDB addr CPI ..",
  "Compare imm byte to byte at rel Z: LDT Z CPI ..",
  "Compare imm byte to byte at rel addr: LDR addr CPI ..",
  "Compare imm word to word in ZP: eval *V – imm",
  "Compare imm word to ZP word: eval *addr – imm",
  "Compare byte in ZP to ZP byte: LDZ Z2 CPZ Z1",
  "Compare byte in ZP to rel ZP addr: LDT Z2 CPZ Z1",
  "Compare byte at adr1 to byte at adr2: LDB adr2 CPB adr1",
  "Compare byte at rel ZP to ZP byte: LDZ Z2 CPT Z1",
  "Compare byte at rel ZP to rel ZP byte: LDT Z2 CPT Z1",
  "Compare word in ZP to ZP word: eval *V2 - *V1",
  "Add imm byte to A with C: A = A + imm + C",
  "Add byte in zero-page to A with C: A = A + *Z + C",
  "Add A to zero-page byte with C: *Z = *Z + A + C",
  "Sub imm byte from A with C: A = A - imm - 1 + C",
  "Sub byte in ZP from A with C: A = A - *Z - 1 + C",
  "Sub A from zero-page byte with C: *Z = *Z - A - 1 + C",
  "internal use",
];

const argss = [
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03,
  0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x01, 0x02,
  0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04,
  0x04, 0x04, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00, 0x00, 0x00, 0x01, 0x01, 0x13, 0x03, 0x03,
  0x32, 0x13, 0x03, 0x01, 0x02, 0x03, 0x02, 0x03, 0x01, 0x03, 0x12, 0x32, 0x02, 0x03, 0x02, 0x03, 0x12, 0x21, 0x31, 0x21, 0x31, 0x23, 0x33,
  0x22, 0x32, 0x22, 0x32, 0x23, 0x33, 0x23, 0x33, 0x22, 0x32, 0x22, 0x32, 0x23, 0x33, 0x23, 0x33, 0x22, 0x23, 0x00, 0x02, 0x03, 0x02, 0x03,
  0x02, 0x03, 0x02, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02,
  0x03, 0x02, 0x03, 0x02, 0x21, 0x31, 0x21, 0x31, 0x21, 0x31, 0x21, 0x22, 0x22, 0x22, 0x22, 0x33, 0x33, 0x22, 0x22, 0x22, 0x01, 0x02, 0x03,
  0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x21, 0x31, 0x21, 0x31, 0x21, 0x31, 0x21, 0x22, 0x22, 0x22, 0x22, 0x33, 0x33, 0x22,
  0x22, 0x22, 0x01, 0x02, 0x03, 0x02, 0x03, 0x21, 0x31, 0x21, 0x31, 0x23, 0x33, 0x22, 0x22, 0x33, 0x22, 0x22, 0x22, 0x01, 0x02, 0x02, 0x01,
  0x02, 0x02, 0x00,
];

const argHelp = [
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "-",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "addr",
  "Z",
  "addr",
  "-",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "-",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr lsb",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "addr",
  "-",
  "-",
  "-",
  "offset",
  "offset",
  "addr,bnk",
  "addr",
  "page,bnk",
  "Z,page,bnk",
  "addr,bnk",
  "addr",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "page",
  "addr",
  "Z,page",
  "Z,addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z,page",
  "imm,Z",
  "imm,addr",
  "imm,Z",
  "imm,addr",
  "imm,V",
  "imm,addr",
  "Z1,Z2",
  "Z,addr",
  "Z1,Z2",
  "Z,addr",
  "addr,Z",
  "adr1,adr2",
  "addr,Z",
  "adr1,adr2",
  "Z1,Z2",
  "Z,addr",
  "Z1,Z2",
  "Z,addr",
  "addr,Z",
  "adr1,adr2",
  "addr,Z",
  "adr1,adr2",
  "V1,V2",
  "addr,V",
  "-",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "addr",
  "Z",
  "-",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "-",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "imm,Z",
  "imm,addr",
  "imm,Z",
  "imm,addr",
  "imm,V",
  "imm,addr",
  "imm,Q",
  "Z1,Z2",
  "Z1,Z2",
  "Z,V",
  "Z,Q",
  "adr1,adr2",
  "ad1,ad2",
  "Z1,Z2",
  "Z1,Z2",
  "V1,V2",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "Z",
  "addr",
  "V",
  "addr",
  "Q",
  "imm,Z",
  "imm,addr",
  "imm,Z",
  "imm,addr",
  "imm,V",
  "imm,addr",
  "imm,Q",
  "Z1,Z2",
  "Z1,Z2",
  "Z,V",
  "Z,Q",
  "adr1,adr2",
  "adr1,adr2",
  "Z1,Z2",
  "Z1,Z2",
  "V1,V2",
  "imm",
  "Z",
  "addr",
  "Z",
  "addr",
  "imm,Z",
  "imm,addr",
  "imm,Z",
  "imm,addr",
  "imm,V",
  "imm,addr",
  "Z1,Z2",
  "Z1,Z2",
  "adr1,adr2",
  "Z1,Z2",
  "adr1,adr2",
  "V1,V2",
  "imm",
  "Z",
  "Z",
  "imm",
  "Z",
  "Z",
  "-",
];

const getArgTypeDescription = (x: number) => {
  switch (x) {
    case 0:
      return "none";
    case 1:
      return "byte";
    case 2:
      return "zero-page";
    case 3:
      return "word";
    case 4:
      return "fast-jump";
  }
};

interface IInstructionInfo {
  opcode: number;
  hex: string;
  instr: string;
  help: string;
  argType: number[];
  argSize: number[];
  totalSize: number;
  hover: string;
}

export const instructionInfo = Array(255)
  .fill(0)
  .reduce<Record<string, IInstructionInfo>>((acc, _, i) => {
    const opcode = i;
    const hex = i.toString(16).toUpperCase().padStart(2, "0");
    const instr = mne[i];
    const help = helps[i];
    let argType: number[] = [];
    let argSize: number[] = [];
    let x = argss[i] & 0x0f;
    if (x != 0) {
      argType.push(x);
      argSize.push(x == 3 ? 2 : 1);
    }
    x = (argss[i] & 0xf0) >> 4;
    if (x != 0) {
      argType.push(x);
      argSize.push(x == 3 ? 2 : 1);
    }
    if (instr == "RZP") {
      argType = [2, 1, 1];
      argSize = [1, 1, 1];
    }
    const totalSize = argSize.reduce((size, cur) => (size += cur), 0);

    const hover = [
      `### ${instr}: *${help}*`,
      `Args: ${argHelp[i]
        .split(",")
        .map((a, j) => `**${a}**:${getArgTypeDescription(argType[j])}`)
        .join(", ")}`,
    ].join("\n");

    acc[instr] = { opcode, hex, instr, help, argType, argSize, totalSize, hover };
    return acc;
  }, {});
