// argument info: bits0-3: argtype1, bits 4-7: argtype2
// types: 0=none, 1=expect byte, 2=zero page, 3=expect word, 4=fast jump

const mens = [
  "NOP",
  "OUT",
  "INT",
  "INK",
  "WIN",
  "SEC",
  "CLC",
  "LL0",
  "LL1",
  "LL2",
  "LL3",
  "LL4",
  "LL5",
  "LL6",
  "LL7",
  "RL0",
  "RL1",
  "RL2",
  "RL3",
  "RL4",
  "RL5",
  "RL6",
  "RL7",
  "RR1",
  "LR0",
  "LR1",
  "LR2",
  "LR3",
  "LR4",
  "LR5",
  "LR6",
  "LR7",
  "LLZ",
  "LLB",
  "LLV",
  "LLW",
  "LLQ",
  "LLL",
  "LRZ",
  "LRB",
  "RLZ",
  "RLB",
  "RLV",
  "RLW",
  "RLQ",
  "RLL",
  "RRZ",
  "RRB",
  "NOT",
  "NOZ",
  "NOB",
  "NOV",
  "NOW",
  "NOQ",
  "NOL",
  "NEG",
  "NEZ",
  "NEB",
  "NEV",
  "NEW",
  "NEQ",
  "NEL",
  "ANI",
  "ANZ",
  "ANB",
  "ANT",
  "ANR",
  "AN.Z",
  "AN.B",
  "ORI",
  "ORZ",
  "ORB",
  "ORT",
  "ORR",
  "OR.Z",
  "OR.B",
  "XRI",
  "XRZ",
  "XRB",
  "XRT",
  "XRR",
  "XR.Z",
  "XR.B",
  "FNE",
  "FEQ",
  "FCC",
  "FCS",
  "FPL",
  "FMI",
  "FGT",
  "FLE",
  "FPA",
  "BNE",
  "BEQ",
  "BCC",
  "BCS",
  "BPL",
  "BMI",
  "BGT",
  "BLE",
  "JPA",
  "JPR",
  "JAR",
  "JPS",
  "JAS",
  "RTS",
  "PHS",
  "PLS",
  "LDS",
  "STS",
  "RDB",
  "RDR",
  "RAP",
  "RZP",
  "WDB",
  "WDR",
  "LDI",
  "LDZ",
  "LDB",
  "LDT",
  "LDR",
  "LAP",
  "LAB",
  "LZP",
  "LZB",
  "STZ",
  "STB",
  "STT",
  "STR",
  "SZP",
  "MIZ",
  "MIB",
  "MIT",
  "MIR",
  "MIV",
  "MIW",
  "MZZ",
  "MZB",
  "MBZ",
  "MBB",
  "MVV",
  "MWV",
  "CLZ",
  "CLB",
  "CLV",
  "CLW",
  "CLQ",
  "CLL",
  "INC",
  "INZ",
  "INB",
  "INV",
  "INW",
  "INQ",
  "INL",
  "DEC",
  "DEZ",
  "DEB",
  "DEV",
  "DEW",
  "DEQ",
  "DEL",
  "ADI",
  "ADZ",
  "ADB",
  "ADT",
  "ADR",
  "AD.Z",
  "AD.B",
  "AD.T",
  "AD.R",
  "ADV",
  "ADW",
  "ADQ",
  "ADL",
  "AIZ",
  "AIB",
  "AIT",
  "AIR",
  "AIV",
  "AIW",
  "AIQ",
  "AIL",
  "AZZ",
  "AZB",
  "AZV",
  "AZW",
  "AZQ",
  "AZL",
  "ABZ",
  "ABB",
  "ABV",
  "ABW",
  "ABQ",
  "AVV",
  "SUI",
  "SUZ",
  "SUB",
  "SUT",
  "SUR",
  "SU.Z",
  "SU.B",
  "SU.T",
  "SU.R",
  "SUV",
  "SUW",
  "SUQ",
  "SUL",
  "SIZ",
  "SIB",
  "SIT",
  "SIR",
  "SIV",
  "SIW",
  "SIQ",
  "SIL",
  "SZZ",
  "SZB",
  "SZV",
  "SZW",
  "SZQ",
  "SZL",
  "SBZ",
  "SBB",
  "SBV",
  "SBW",
  "SBQ",
  "SVV",
  "CPI",
  "CPZ",
  "CPB",
  "CPT",
  "CPR",
  "CIZ",
  "CIB",
  "CIT",
  "CIR",
  "CZZ",
  "CZB",
  "CBZ",
  "CBB",
  "ACI",
  "ACZ",
  "ACB",
  "AC.Z",
  "AC.B",
  "ACV",
  "ACW",
  "SCI",
  "SCZ",
  "SCB",
  "SC.Z",
  "SC.B",
  "SCV",
  "SCW",
  "-",
];

const helps = [
  "No operation",
  "Output A to UART: UART = A",
  "Read UART input to A: A = UART",
  "Read PS/2 input to A: A = PS2",
  "Wait for input",
  "Set carry flag (C=1)",
  "Clear carry flag (C=0)",
  "Logical left-shift A 0 steps (C=0)",
  "Logical left-shift A 1 step (C=0)",
  "Logical left-shift A 2 steps (C=0)",
  "Logical left-shift A 3 steps (C=0)",
  "Logical left-shift A 4 steps (C=0)",
  "Logical left-shift A 5 steps (C=0)",
  "Logical left-shift A 6 steps (C=0)",
  "Logical left-shift A 7 steps (C=0)",
  "Rotate left A 0 steps via C (= RR9)",
  "Rotate left A 1 step via C (= RR8)",
  "Rotate left A 2 steps via C (= RR7)",
  "Rotate left A 3 steps via C (= RR6)",
  "Rotate left A 4 steps via C (= RR5)",
  "Rotate left A 5 steps via C (= RR4)",
  "Rotate left A 6 steps via C (= RR3)",
  "Rotate left A 7 steps via C (= RR2)",
  "Rotate right A 1 step via C (= RL8)",
  "Logical right-shift A 0 steps (C=0) (= RR0, RL9)",
  "Logical right-shift A 1 step (C=0)",
  "Logical right-shift A 2 steps (C=0) §",
  "Logical right-shift A 3 steps (C=0) §",
  "Logical right-shift A 4 steps (C=0) §",
  "Logical right-shift A 5 steps (C=0) §",
  "Logical right-shift A 6 steps (C=0) §",
  "Logical right-shift A 7 steps (C=0)",
  "Logical shift left *Z 1 step (C=0)",
  "Logical shift byte left 1 step (C=0)",
  "Logical shift fast word left 1 step (C=0)",
  "Logical shift word left 1 step (C=0)",
  "Logical shift fast long left 1 step (C=0)",
  "Logical shift long left 1 step (C=0)",
  "Logical shift right zero-page byte 1 step (C=0)",
  "Logical shift right abs byte 1 step (C=0)",
  "Rotate left zero-page byte 1 step via C",
  "Rotate left byte at abs addr 1 step via C",
  "Rotate left zero-page word 1 step via C",
  "Rotate left word at abs addr 1 step via C",
  "Rotate left zero-page long 1 step via C",
  "Rotate left abs long 1 step via C",
  "Rotate right zero-page byte 1 step via C",
  "Rotate right byte at abs addr 1 step via C",
  "Bitwise NOT A: A = ~A",
  "Bitwise NOT *Z: *Z = ~(*Z)",
  "Bitwise NOT byte: *addr = ~(*addr)",
  "Bitwise NOT zero-page word: *V = ~(*V)",
  "Bitwise NOT word at abs address",
  "Bitwise NOT zero-page long",
  "Bitwise NOT long at abs address",
  "Negate A: A = -A",
  "Negate zero-page byte: *Z = -(*Z)",
  "Negate byte at abs address: *addr = -(*addr)",
  "Negate zero-page word (C = 1 only if word=0)",
  "Negate word at abs address (C = 1 only if word=0)",
  "Negate zero-page long (C = 1 only if long = 0)",
  "Negate long (C = 1 only if long = 0)",
  "Bitwise AND: A = A & imm",
  "Bitwise AND: A = A & *Z",
  "Bitwise AND: A = A & *addr",
  "Bitwise AND: A = A & *(*Z)",
  "Bitwise AND: A = A & *(*addr)",
  "Bitwise AND: *Z = *Z & A",
  "Bitwise AND: *addr = *addr & A",
  "Bitwise OR: A = A | imm",
  "Bitwise OR: A = A | *Z",
  "Bitwise OR: A = A | *addr",
  "Bitwise OR: A = A | *(*Z)",
  "Bitwise OR: A = A | *(*addr)",
  "Bitwise OR: *Z = *Z | A",
  "Bitwise OR: *addr = *addr | A",
  "Bitwise XOR: A = A ^ imm §",
  "Bitwise XOR: A = A ^ *Z",
  "Bitwise XOR: A = A ^ * addr §",
  "Bitwise XOR: A = A ^ *(*Z)",
  "Bitwise XOR: A = A ^ *(*addr) §",
  "Bitwise XOR: *Z = *Z ^ A",
  "Bitwise XOR: *addr = *addr ^ A",
  "Fast branch on non-zero",
  "Fast branch on zero",
  "Fast branch on carry clear",
  "Fast branch on carry set",
  "Fast branch on plus",
  "Fast branch on minus",
  "Fast branch on greater",
  "Fast branch on less or equal",
  "Fast jump to lsb addr",
  "Branch on non-zero",
  "Branch on zero",
  "Branch on carry clear",
  "Branch on carry set",
  "Branch on plus",
  "Branch on minus",
  "Branch on greater",
  "Branch on less or equal",
  "Jump to abs address: PC = addr",
  "Jump to rel address: PC = *addr",
  "Jump A-indexed to rel address: PC = *(addr + A)",
  "Jump to subroutine",
  "Jump to subroutine conserving A §",
  "Return from subroutine",
  "Push A onto stack",
  "Pull A from stack",
  "Load from stack: A = *(0xff00 + SP + off)",
  "Store on stack: *(0xff00 + SP + off) = A",
  "Read FLASH data from abs 3-byte address",
  "Read FLASH data from rel 3-byte address",
  "Read A-indexed FLASH data: A = *(pg<<8 + A)",
  "Read Z-indexed FLASH data: A = *(pg<<8 + *Z)",
  "Write FLASH data to abs 3-byte address §",
  "Write FLASH data to rel 3-byte address §",
  "Load A immediate: A = imm",
  "Load A from Z: A = *Z",
  "Load A from abs address: A = *addr",
  "Load A from rel address in zero page: A = *(*Z)",
  "Load A from relative address: A = *(*addr)",
  "Load A A-indexed from page: A = *(pg<<8 + A)",
  "Load A A-indexed from addr: A = *(addr + A)",
  "Load A Z-indexed from page: A = *(pg<<8 + *Z)",
  "Load A Z-indexed from addr: A = *(addr + *Z)",
  "Store A to Z: *Z = A",
  "Store A to address: *addr = A",
  "Store A at rel address in zero page: *(*Z) = A",
  "Store A at relative address: *(*addr) = A",
  "Store A Z-indexed to page: *(pg<<8 + *Z) = A",
  "Move imm byte to zero-page: *Z = imm",
  "Move imm byte to abs addr: *addr = imm",
  "Move imm byte to rel zero-page addr: *(*T) = imm",
  "Move imm byte to rel addr: *(*addr) = imm",
  "Move imm word to zero-page word: *V = imm",
  "Move imm word to abs addr: *addr = imm",
  "Move zero-page byte to zero-page byte: *Z2 = *Z1",
  "Move zero-page byte to abs addr: *addr = *Z",
  "Move byte at abs addr to zero-page: *Z = *addr",
  "Move byte from abs adr1 to abs adr2: *adr2 = *adr1",
  "Move zero-page word to zero-page word: *V2 = *V1",
  "Move word at abs addr to fast word: *V = *addr",
  "Clear Z: *Z = 0x00",
  "Clear byte at addr: *addr = 0x00",
  "Clear fast word: *V = 0x0000",
  "Clear word at addr: *addr = 0x0000",
  "Clear zero-page long: *Q = 0x00000000",
  "Clear long: *addr = 0x00000000",
  "Increment A: A = A + 1",
  "Increment zero-page byte: *Z = *Z + 1",
  "Increment byte at abs addr: *addr = *addr + 1",
  "Increment zero-page word: *V = *V + 0x0001",
  "Increment word at abs addr: *addr = *addr + 0x0001",
  "Increment zero-page long: *Q = *Q + 0x00000001",
  "Increment long: *addr = *addr + 0x00000001",
  "Decrement A: A = A - 1",
  "Decrement *Z = *Z - 1",
  "Decrement byte: *addr = *addr - 1",
  "Decrement zero-page word: *V = *V - 0x0001",
  "Decrement word at abs addr: *addr = *addr - 0x0001",
  "Decrement zero-page long: *Q = *Q - 0x00000001",
  "Decrement long: *addr = *addr - 0x00000001",
  "Add immediate to A: A = A + imm",
  "Add zero-page byte to A: A = A + *Z",
  "Add byte at addr to A: A = A + *addr",
  "Add byte at rel zero-page addr to A: A = A + *(*Z)",
  "Add byte at rel addr to A: A = A + *(*addr)",
  "Add A to zero-page byte: *Z = *Z + A",
  "Add A to byte at abs addr: *addr = *addr + A",
  "Add A to rel zero-page address: *(*Z) = *(*Z) + A",
  "Add A to rel address: *(*addr) = *(*addr) + A",
  "Add A to zero-page word: *V = *V + A",
  "Add A to word at abs addr: *addr = *addr + A",
  "Add A to zero-page long: *Q = *Q + A",
  "Add A to long: *addr = *addr + A",
  "Add immediate to zero-page byte: *Z = *Z + imm",
  "Add imm to byte at abs addr: *addr = *addr + imm",
  "Add imm to byte at rel Z addr: *(*Z) = *(*Z) + imm",
  "Add imm to byte at rel addr: *(*adr) = *(*adr) + imm",
  "Add immediate byte to zero-page word: *V = *V + imm",
  "Add imm byte to abs word: *addr = *addr + imm",
  "Add immediate byte to zero-page long: *Q = *Q + imm",
  "Add immediate byte to long: *L = *L + imm",
  "Add zero-page byte to zero-page byte: *Z2 = *Z2 + *Z1",
  "Add zero-page to byte at abs addr: *addr = *addr + *Z",
  "Add zero-page byte to zero-page word: *V = *V + *Z",
  "Add zero-page byte to word at addr: *addr = *addr + *Z",
  "Add zero-page byte to zero-page long: *Q = *Q + *Z",
  "Add zero-page byte to long: *L = *L + *Z",
  "Add abs byte to zero-page byte: *Z = *Z + *addr",
  "Add abs byte to byte: *adr2 = *adr2 + *adr1",
  "Add abs byte to zero-page word: *V = *V + *addr",
  "Add byte at ad1 to word at ad2: *ad2 = *ad2 + *ad1",
  "Add abs byte to zero-page long: *Q = *Q + *addr",
  "Add zero-page word to zero-page word: *V2 = *V2 + *V1",
  "Sub immediate from A: A = A - imm",
  "Sub zero-page byte from A: A = A - *Z",
  "Sub byte at addr from A: A = A - *addr",
  "Sub byte at rel zero-page addr from A: A = A - *(*Z)",
  "Sub byte at rel addr from A: A = A - *(*addr)",
  "Sub A from zero-page byte: *Z = *Z - A",
  "Sub A from byte at abs addr: *addr = *addr - A",
  "Sub A from rel zero-page address: *(*Z) = *(*Z) - A",
  "Sub A from byte at rel addr: *(*addr) = *(*addr) - A",
  "Sub A from zero-page word: *v = *V - A",
  "Sub A from word at abs addr: *addr = *addr - A",
  "Sub A from zero-page long: *Q = *Q - A",
  "Sub A from long: *addr = *addr - A",
  "Sub immediate from zero-page byte: *Z = *Z - imm",
  "Sub imm from byte: *addr = *addr - imm",
  "Sub imm from byte at rel Z addr: *(*Z) = *(*Z) + imm",
  "Sub imm from byte at rel addr: *(*ad) = *(*ad) + imm",
  "Sub imm byte from zero-page word: *V = *V - imm",
  "Sub imm byte from abs word: *addr = *addr - imm",
  "Sub imm byte from zero-page long Z: *Z = *Z - imm",
  "Sub imm byte from long at abs address: *L = *L - imm",
  "Sub zero-page byte from Z byte: *Z2 = *Z2 - *Z1",
  "Sub zero-page byte from abs byte: *addr = *addr - *Z",
  "Sub zero-page byte from zero-page word: *V = *V - *Z",
  "Sub zero-page byte from abs word: *addr = *addr - *Z",
  "Sub zero-page byte from zero-page long: *Q = *Q - *Z",
  "Sub zero-page byte from long: *L = *L - *Z",
  "Sub abs byte from zero-page byte: *Z = *Z - *addr",
  "Sub abs byte from byte: *adr2 = *adr2 - *adr1",
  "Sub abs byte from zero-page word: *V = *V - *addr",
  "Sub abs byte from word at adr2: *adr2 = *adr2 - *adr1",
  "Sub abs byte from zero-page long: *Q = *Q - *addr",
  "Sub zero-page word from word: *V2 = *V2 - *V1",
  "Compare immediate value to A: eval A - imm",
  "Compare zero-page byte to A: eval A - *Z",
  "Compare byte at addr to A: eval A - *addr",
  "Compare byte at rel Z to A: eval A - *(*Z)",
  "Compare rel byte to A: eval A - *(*addr)",
  "Compare imm to zero-page byte: A = *Z - imm",
  "Compare imm to byte at abs addr: A = *addr - imm",
  "Compare imm to byte at rel Z: A = *(*Z) - imm",
  "Compare imm to byte at rel addr: A = *(*addr) - imm",
  "Compare zero-page byte to byte: A = *Z2 - *Z1",
  "Compare zero-page byte to byte: A = *addr - *Z",
  "Compare abs byte to zero-page byte: A = *addr - *Z",
  "Compare abs byte to byte: A = *adr2 - *adr1",
  "Add immediate value to A with C: A = A + imm + C",
  "Add zero-page byte with C to A: A = A + *Z + C",
  "Add byte at addr with C to A: A = A + *addr + C",
  "Add A with C to zero-page byte: *Z = *Z + A + C",
  "Add A with C to byte at addr: *addr = *addr + A + C",
  "Add A with C to zero-page word",
  "Add A with C to word at ads addr: *adr = *adr + A + C",
  "Sub imm value from A with C: A = A - imm - 1 + C",
  "Sub zero-page byte with C from A: A = A - *Z - 1 + C",
  "Sub byte at addr from A with C: A = A - *addr - 1 + C",
  "Sub A with C from zero-page byte: *Z = *Z - A - 1 + C",
  "Sub A with C from byte: *addr = *addr - A - 1 + C",
  "Sub A with C from zero-page word",
  "Sub A with C from word at abs addr",
  "Set bank register to 0xff (FLASH OFF) after boot-up",
];

const argss = [
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03,
  0x02, 0x03, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03,
  0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04, 0x04,
  0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x03, 0x00, 0x00, 0x00, 0x01, 0x01, 0x13, 0x03, 0x03, 0x32, 0x13,
  0x03, 0x01, 0x02, 0x03, 0x02, 0x03, 0x01, 0x03, 0x12, 0x32, 0x02, 0x03, 0x02, 0x03, 0x12, 0x21, 0x31, 0x21, 0x31, 0x23, 0x33, 0x22, 0x32,
  0x23, 0x33, 0x22, 0x23, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x00, 0x02, 0x03, 0x02, 0x03, 0x02,
  0x03, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x21, 0x31, 0x21, 0x31, 0x21, 0x31, 0x21, 0x31, 0x22,
  0x32, 0x22, 0x32, 0x22, 0x32, 0x23, 0x33, 0x23, 0x33, 0x23, 0x22, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x02,
  0x03, 0x21, 0x31, 0x21, 0x31, 0x21, 0x31, 0x21, 0x31, 0x22, 0x32, 0x22, 0x32, 0x22, 0x32, 0x23, 0x33, 0x23, 0x33, 0x23, 0x22, 0x01, 0x02,
  0x03, 0x02, 0x03, 0x21, 0x31, 0x21, 0x31, 0x22, 0x32, 0x23, 0x33, 0x01, 0x02, 0x03, 0x02, 0x03, 0x02, 0x03, 0x01, 0x02, 0x03, 0x02, 0x03,
  0x02, 0x03, 0x00,
];

interface IInstructionInfo {
  opcode: number;
  hex: string;
  instr: string;
  help: string;
  args: number;
}

export const instructionInfo = Array(255)
  .fill(0)
  .reduce<Record<string, IInstructionInfo>>((acc, _, i) => {
    const opcode = i;
    const hex = i.toString(16).toUpperCase().padStart(2, "0");
    const instr = mens[i];
    const help = helps[i];
    const args = argss[i];
    acc[instr] = { opcode, hex, instr, help, args };
    return acc;
  }, {});

// console.log(
//   Object.values(instructionInfo)
//     .filter((info) => info.args == 0)
//     .map((info) => `"${info.instr}"`)
//     .join("|"),
// );
// console.log(
//   Object.values(instructionInfo)
//     .filter((info) => (info.args & 0x0f) != 0 && (info.args & 0xf0) == 0)
//     .map((info) => `"${info.instr}"`)
//     .join("|"),
// );
// console.log(
//   Object.values(instructionInfo)
//     .filter((info) => (info.args & 0xf0) != 0)
//     .map((info) => `"${info.instr}"`)
//     .join("|"),
// );
