#org 0x2000

JPS _Clear
loop3:          JPS _Random CPI 200 FCS loop3                 ; draw random lines
                  LL1 STZ 0x80 LDI 0 RL1 STZ 0x81
                  JPS _Random ANI 1 OR.Z 0x80
  loop71:       JPS _Random CPI 240 FCS loop71 STZ 0x82
  loop72:       JPS _Random CPI 200 FCS loop72
                  LL1 STZ 0x83 LDI 0 RL1 STZ 0x84
                  JPS _Random ANI 1 OR.Z 0x83
  loop6:        JPS _Random CPI 240 FCS loop6 STZ 0x85
                JPS _ScanPS2 ;0x2041
                JPS _Line
                JPS _ReadInput CPI 0 BEQ loop3

done:
      JPA _Prompt

#org 0x0080     
xa: 0x008b                             ; zero-page graphics interface (OS_SetPixel, OS_ClearPixel, OS_Line, OS_Rect)
ya: 0x34
xb: 0x0029
yb: 0xe8

;
#mute ; MinOS API definitions generated by 'asm os.asm -s_'

#org 0xf000 _Start:
#org 0xf003 _Prompt:
#org 0xf006 _MemMove:
#org 0xf009 _Random:
#org 0xf00c _ScanPS2:
#org 0xf00f _ResetPS2:
#org 0xf012 _ReadInput:
#org 0xf015 _WaitInput:
#org 0xf018 _ReadLine:
#org 0xf01b _SkipSpace:
#org 0xf01e _ReadHex:
#org 0xf021 _SerialWait:
#org 0xf024 _SerialPrint:
#org 0xf027 _FindFile:
#org 0xf02a _LoadFile:
#org 0xf02d _SaveFile:
#org 0xf030 _ClearVRAM:
#org 0xf033 _Clear:
#org 0xf036 _ClearRow:
#org 0xf039 _ScrollUp:
#org 0xf03c _ScrollDn:
#org 0xf03f _Char:
#org 0xf042 _PrintChar:
#org 0xf045 _Print:
#org 0xf048 _PrintPtr:
#org 0xf04b _PrintHex:
#org 0xf04e _SetPixel:
#org 0xf051 _Line:
#org 0xf054 _Rect:
#org 0x00c0 _XPos:
#org 0x00c1 _YPos:
#org 0x00c2 _RandomState:
#org 0x00c6 _ReadNum:
#org 0x00c9 _ReadPtr:
#org 0x00cd _ReadBuffer:
