/**
 * Full 256-entry opcode metadata table, transcribed from the 'Minimal 64x4 Redux
 * Instruction Set' reference spreadsheet. Used by the disassembler and available for
 * tooling/documentation purposes. This table is NOT used by the CPU's execute() path
 * (which implements each opcode's semantics directly) - it exists for introspection.
 */
export interface OpcodeInfo {
  mnemonic: string;
  description: string;
  operandBytes: number;
}

export const OPCODE_TABLE: readonly OpcodeInfo[] = [
  { mnemonic: "NOP", description: "No operation", operandBytes: 0 },
  { mnemonic: "OUT", description: "Output A to UART: UART = A", operandBytes: 0 },
  { mnemonic: "INT", description: "Read UART input to A: A = UART", operandBytes: 0 },
  { mnemonic: "INK", description: "Read PS/2 input to A: A = PS2", operandBytes: 0 },
  { mnemonic: "WIN", description: "Wait for any input (UART or PS/2)", operandBytes: 0 },
  { mnemonic: "LL0", description: "Logical left-shift A 0 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LL1", description: "Logical left-shift A 1 step (C=0)", operandBytes: 0 },
  { mnemonic: "LL2", description: "Logical left-shift A 2 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LL3", description: "Logical left-shift A 3 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LL4", description: "Logical left-shift A 4 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LL5", description: "Logical left-shift A 5 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LL6", description: "Logical left-shift A 6 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LL7", description: "Logical left-shift A 7 steps (C=0)", operandBytes: 0 },
  { mnemonic: "RL0", description: "Rotate left A 0 steps via C (= RR9)", operandBytes: 0 },
  { mnemonic: "RL1", description: "Rotate left A 1 step via C (= RR8)", operandBytes: 0 },
  { mnemonic: "RL2", description: "Rotate left A 2 steps via C (= RR7)", operandBytes: 0 },
  { mnemonic: "RL3", description: "Rotate left A 3 steps via C (= RR6)", operandBytes: 0 },
  { mnemonic: "RL4", description: "Rotate left A 4 steps via C (= RR5)", operandBytes: 0 },
  { mnemonic: "RL5", description: "Rotate left A 5 steps via C (= RR4)", operandBytes: 0 },
  { mnemonic: "RL6", description: "Rotate left A 6 steps via C (= RR3)", operandBytes: 0 },
  { mnemonic: "RL7", description: "Rotate left A 7 steps via C (= RR2)", operandBytes: 0 },
  { mnemonic: "RR1", description: "Rotate right A 1 step via C (= RL8)", operandBytes: 0 },
  { mnemonic: "LR0", description: "Logical right-shift A 0 steps (C=0) (= RR0, RL9)", operandBytes: 0 },
  { mnemonic: "LR1", description: "Logical right-shift A 1 step (C=0)", operandBytes: 0 },
  { mnemonic: "LR2", description: "Logical right-shift A 2 steps (C=0) §", operandBytes: 0 },
  { mnemonic: "LR3", description: "Logical right-shift A 3 steps (C=0) §", operandBytes: 0 },
  { mnemonic: "LR4", description: "Logical right-shift A 4 steps (C=0) §", operandBytes: 0 },
  { mnemonic: "LR5", description: "Logical right-shift A 5 steps (C=0) §", operandBytes: 0 },
  { mnemonic: "LR6", description: "Logical right-shift A 6 steps (C=0) §", operandBytes: 0 },
  { mnemonic: "LR7", description: "Logical right-shift A 7 steps (C=0)", operandBytes: 0 },
  { mnemonic: "LLZ", description: "Logical shift left *Z 1 step (C=0)", operandBytes: 1 },
  { mnemonic: "LLB", description: "Logical shift byte left 1 step (C=0)", operandBytes: 2 },
  { mnemonic: "LLV", description: "Logical shift fast word left 1 step (C=0)", operandBytes: 1 },
  { mnemonic: "LLW", description: "Logical shift word left 1 step (C=0)", operandBytes: 2 },
  { mnemonic: "LLQ", description: "Logical shift fast long left 1 step (C=0)", operandBytes: 1 },
  { mnemonic: "LLL", description: "Logical shift long left 1 step (C=0)", operandBytes: 2 },
  { mnemonic: "LRZ", description: "Logical shift right zero-page byte 1 step (C=0)", operandBytes: 1 },
  { mnemonic: "LRB", description: "Logical shift right abs byte 1 step (C=0)", operandBytes: 2 },
  { mnemonic: "RLZ", description: "Rotate left zero-page byte 1 step via C", operandBytes: 1 },
  { mnemonic: "RLB", description: "Rotate left byte at addr 1 step via C", operandBytes: 2 },
  { mnemonic: "RLV", description: "Rotate left zero-page word 1 step via C", operandBytes: 1 },
  { mnemonic: "RLW", description: "Rotate left word at addr 1 step via C", operandBytes: 2 },
  { mnemonic: "RLQ", description: "Rotate left zero-page long 1 step via C", operandBytes: 1 },
  { mnemonic: "RLL", description: "Rotate left abs long 1 step via C", operandBytes: 2 },
  { mnemonic: "RRZ", description: "Rotate right zero-page byte 1 step via C", operandBytes: 1 },
  { mnemonic: "RRB", description: "Rotate right byte at addr 1 step via C", operandBytes: 2 },
  { mnemonic: "NOT", description: "Bitwise NOT A: A = ~A", operandBytes: 0 },
  { mnemonic: "NOZ", description: "Bitwise NOT *Z: *Z = ~*Z", operandBytes: 1 },
  { mnemonic: "NOB", description: "Bitwise NOT byte: *addr = ~*addr", operandBytes: 2 },
  { mnemonic: "NOV", description: "Bitwise NOT zero-page word: *V = ~(*V)", operandBytes: 1 },
  { mnemonic: "NOW", description: "Bitwise NOT word at address", operandBytes: 2 },
  { mnemonic: "NOQ", description: "Bitwise NOT zero-page long", operandBytes: 1 },
  { mnemonic: "NEG", description: "Negate A: A = -A", operandBytes: 0 },
  { mnemonic: "NEZ", description: "Negate zero-page byte: *Z = -*Z", operandBytes: 1 },
  { mnemonic: "NEB", description: "Negate byte at address: *addr = -*addr", operandBytes: 2 },
  { mnemonic: "NEV", description: "Negate zero-page word (C = 1 only if word = 0)", operandBytes: 1 },
  { mnemonic: "NEW", description: "Negate word at address (C = 1 only if word = 0)", operandBytes: 2 },
  { mnemonic: "NEQ", description: "Negate zero-page long (C = 1 only if long = 0)", operandBytes: 1 },
  { mnemonic: "ANI", description: "Bitwise AND: A = A & imm", operandBytes: 1 },
  { mnemonic: "ANZ", description: "Bitwise AND: A = A & *Z", operandBytes: 1 },
  { mnemonic: "ANB", description: "Bitwise AND: A = A & *addr", operandBytes: 2 },
  { mnemonic: "ANT", description: "Bitwise AND: A = A & **Z", operandBytes: 1 },
  { mnemonic: "ANR", description: "Bitwise AND: A = A & **addr", operandBytes: 2 },
  { mnemonic: "AN.Z", description: "Bitwise AND: *Z = *Z & A", operandBytes: 1 },
  { mnemonic: "AN.B", description: "Bitwise AND: *addr = *addr & A", operandBytes: 2 },
  { mnemonic: "AN.T", description: "Bitwise AND: **Z = A & **Z", operandBytes: 1 },
  { mnemonic: "AN.R", description: "Bitwise AND: **addr = A & **addr", operandBytes: 2 },
  { mnemonic: "ORI", description: "Bitwise OR: A = A | imm", operandBytes: 1 },
  { mnemonic: "ORZ", description: "Bitwise OR: A = A | *Z", operandBytes: 1 },
  { mnemonic: "ORB", description: "Bitwise OR: A = A | *addr", operandBytes: 2 },
  { mnemonic: "ORT", description: "Bitwise OR: A = A | **Z", operandBytes: 1 },
  { mnemonic: "ORR", description: "Bitwise OR: A = A | **addr", operandBytes: 2 },
  { mnemonic: "OR.Z", description: "Bitwise OR: *Z = *Z | A", operandBytes: 1 },
  { mnemonic: "OR.B", description: "Bitwise OR: *addr = *addr | A", operandBytes: 2 },
  { mnemonic: "OR.T", description: "Bitwise OR: **Z = A | **Z", operandBytes: 1 },
  { mnemonic: "OR.R", description: "Bitwise OR: **addr = A | **addr", operandBytes: 2 },
  { mnemonic: "XRI", description: "Bitwise XOR: A = A ^ imm §", operandBytes: 1 },
  { mnemonic: "XRZ", description: "Bitwise XOR: A = A ^ *Z", operandBytes: 1 },
  { mnemonic: "XRB", description: "Bitwise XOR: A = A ^ * addr §", operandBytes: 2 },
  { mnemonic: "XRT", description: "Bitwise XOR: A = A ^ **Z", operandBytes: 1 },
  { mnemonic: "XRR", description: "Bitwise XOR: A = A ^ **addr §", operandBytes: 2 },
  { mnemonic: "XR.Z", description: "Bitwise XOR: *Z = *Z ^ A", operandBytes: 1 },
  { mnemonic: "XR.B", description: "Bitwise XOR: *addr = *addr ^ A", operandBytes: 2 },
  { mnemonic: "XR.T", description: "Bitwise XOR: **Z = A ^ **Z", operandBytes: 1 },
  { mnemonic: "XR.R", description: "Bitwise XOR: **addr = A ^ **addr §", operandBytes: 2 },
  { mnemonic: "FNE", description: "Fast branch on non-zero", operandBytes: 1 },
  { mnemonic: "FEQ", description: "Fast branch on zero", operandBytes: 1 },
  { mnemonic: "FCC", description: "Fast branch on carry clear", operandBytes: 1 },
  { mnemonic: "FCS", description: "Fast branch on carry set", operandBytes: 1 },
  { mnemonic: "FPL", description: "Fast branch on plus", operandBytes: 1 },
  { mnemonic: "FMI", description: "Fast branch on minus", operandBytes: 1 },
  { mnemonic: "FGT", description: "Fast branch on greater", operandBytes: 1 },
  { mnemonic: "FLE", description: "Fast branch on less or equal", operandBytes: 1 },
  { mnemonic: "FPA", description: "Fast jump to lsb addr", operandBytes: 1 },
  { mnemonic: "BNE", description: "Branch on non-zero", operandBytes: 2 },
  { mnemonic: "BEQ", description: "Branch on zero", operandBytes: 2 },
  { mnemonic: "BCC", description: "Branch on carry clear", operandBytes: 2 },
  { mnemonic: "BCS", description: "Branch on carry set", operandBytes: 2 },
  { mnemonic: "BPL", description: "Branch on plus", operandBytes: 2 },
  { mnemonic: "BMI", description: "Branch on minus", operandBytes: 2 },
  { mnemonic: "BGT", description: "Branch on greater", operandBytes: 2 },
  { mnemonic: "BLE", description: "Branch on less or equal", operandBytes: 2 },
  { mnemonic: "JPA", description: "Jump to address: PC = addr", operandBytes: 2 },
  { mnemonic: "JPR", description: "Jump to rel address: PC = *addr", operandBytes: 2 },
  { mnemonic: "JAR", description: "Jump A-indexed to rel address: PC = *(addr + A)", operandBytes: 2 },
  { mnemonic: "JPS", description: "Jump to subroutine", operandBytes: 2 },
  { mnemonic: "JAS", description: "Jump to subroutine conserving A §", operandBytes: 2 },
  { mnemonic: "RTS", description: "Return from subroutine", operandBytes: 0 },
  { mnemonic: "PHS", description: "Push A onto stack", operandBytes: 0 },
  { mnemonic: "PLS", description: "Pull A from stack", operandBytes: 0 },
  { mnemonic: "LDS", description: "Load from stack: A = *(0xff00 + SP + off)", operandBytes: 1 },
  { mnemonic: "SDS", description: "Store on stack: *(0xff00 + SP + off) = A", operandBytes: 1 },
  { mnemonic: "RDB", description: "Read FLASH data from abs 3-byte address", operandBytes: 3 },
  { mnemonic: "RDR", description: "Read FLASH data from rel 3-byte address", operandBytes: 2 },
  { mnemonic: "RAP", description: "Read A-indexed FLASH data: A = *(page<<8 + A)", operandBytes: 2 },
  { mnemonic: "RZP", description: "Read Z-indexed FLASH data: A = *(page<<8 + *Z)", operandBytes: 3 },
  { mnemonic: "WDB", description: "Write FLASH data to abs 3-byte address §", operandBytes: 3 },
  { mnemonic: "WDR", description: "Write FLASH data to rel 3-byte address §", operandBytes: 2 },
  { mnemonic: "LDI", description: "Load A immediate: A = imm", operandBytes: 1 },
  { mnemonic: "LDZ", description: "Load A from Z: A = *Z", operandBytes: 1 },
  { mnemonic: "LDB", description: "Load A from address: A = *addr", operandBytes: 2 },
  { mnemonic: "LDT", description: "Load A from rel address in zero page: A = **Z", operandBytes: 1 },
  { mnemonic: "LDR", description: "Load A from relative address: A = **addr", operandBytes: 2 },
  { mnemonic: "LAP", description: "Load A A-indexed from page: A = *(page<<8 + A)", operandBytes: 1 },
  { mnemonic: "LAB", description: "Load A A-indexed from addr: A = *(addr + A)", operandBytes: 2 },
  { mnemonic: "LZP", description: "Load A Z-indexed from page: A = *(page<<8 + *Z)", operandBytes: 2 },
  { mnemonic: "LZB", description: "Load A Z-indexed from addr: A = *(addr + *Z)", operandBytes: 3 },
  { mnemonic: "SDZ", description: "Store A to Z: *Z = A", operandBytes: 1 },
  { mnemonic: "SDB", description: "Store A to address: *addr = A", operandBytes: 2 },
  { mnemonic: "SDT", description: "Store A at rel address in zero page: **Z = A", operandBytes: 1 },
  { mnemonic: "SDR", description: "Store A at relative address: **addr = A", operandBytes: 2 },
  { mnemonic: "SZP", description: "Store A Z-indexed to page: *(page<<8 + *Z) = A", operandBytes: 2 },
  { mnemonic: "MIZ", description: "Move imm byte to zero-page: *Z = imm", operandBytes: 2 },
  { mnemonic: "MIB", description: "Move imm byte to addr: *addr = imm", operandBytes: 3 },
  { mnemonic: "MIT", description: "Move imm byte to rel zero-page addr: *(*T) = imm", operandBytes: 2 },
  { mnemonic: "MIR", description: "Move imm byte to rel addr: **addr = imm", operandBytes: 3 },
  { mnemonic: "MIV", description: "Move imm word to zero-page word: *V = imm", operandBytes: 3 },
  { mnemonic: "MIW", description: "Move imm word to addr: *addr = imm", operandBytes: 4 },
  { mnemonic: "MZZ", description: "Move byte at ZP addr to zero-page addr: *Z2 = *Z1", operandBytes: 2 },
  { mnemonic: "MZB", description: "Move byte at ZP addr to addr: *addr = *Z", operandBytes: 3 },
  { mnemonic: "MZT", description: "Move byte at ZP addr to rel ZP addr: **Z2 = *Z1", operandBytes: 2 },
  { mnemonic: "MZR", description: "Move byte at ZP addr to rel addr: **addr = *Z1", operandBytes: 3 },
  { mnemonic: "MBZ", description: "Move byte at addr to zero-page: *Z = *addr", operandBytes: 3 },
  { mnemonic: "MBB", description: "Move byte at adr1 to adr2: *adr2 = *adr1", operandBytes: 4 },
  { mnemonic: "MBT", description: "Move byte at addr to rel ZP addr: **Z = *addr", operandBytes: 3 },
  { mnemonic: "MBR", description: "Move byte at adr1 to rel adr2: **adr2 = *adr1", operandBytes: 4 },
  { mnemonic: "MTZ", description: "Move byte at rel ZP addr to ZP addr: *Z2 = **Z1", operandBytes: 2 },
  { mnemonic: "MTB", description: "Move byte at rel ZP addr to addr: *addr = **Z", operandBytes: 3 },
  { mnemonic: "MTT", description: "Move byte at rel ZP adr to rel ZP adr: **Z2 = **Z1", operandBytes: 2 },
  { mnemonic: "MTR", description: "Move byte at rel ZP addr to rel addr: **addr = **Z", operandBytes: 3 },
  { mnemonic: "MRZ", description: "Move byte at rel addr to ZP addr: *Z = **addr", operandBytes: 3 }, // spreadsheet left the size cell blank; addr(2)+Z(1), matching MBZ/MTZ siblings
  { mnemonic: "MRB", description: "Move byte at rel adr1 to adr2: *adr2 = **adr1", operandBytes: 4 },
  { mnemonic: "MRT", description: "Move byte at rel addr to rel ZP addr: **Z = **addr", operandBytes: 3 },
  { mnemonic: "MRR", description: "Move byte at rel adr1 to rel adr2: **adr2 = **adr1", operandBytes: 4 },
  { mnemonic: "MVV", description: "Move word at ZP addr to word at ZP addr: *V2 = *V1", operandBytes: 2 },
  { mnemonic: "MWV", description: "Move word at addr to word at ZP addr: *V = *addr", operandBytes: 3 },
  { mnemonic: "CLD", description: "Clear A: A = 0x00", operandBytes: 0 },
  { mnemonic: "CLZ", description: "Clear byte at zero-page addr: *Z = 0x00", operandBytes: 1 },
  { mnemonic: "CLB", description: "Clear byte at addr: *addr = 0x00", operandBytes: 2 },
  { mnemonic: "CLV", description: "Clear word at zero-page addr: *V = 0x0000", operandBytes: 1 },
  { mnemonic: "CLW", description: "Clear word at addr: *addr = 0x0000", operandBytes: 2 },
  { mnemonic: "CLQ", description: "Clear long at zero-page addr: *Q = 0x00000000", operandBytes: 1 },
  { mnemonic: "CLL", description: "Clear long at addr: *addr = 0x00000000", operandBytes: 2 },
  { mnemonic: "CL5", description: "Clear data at rel ZP: **Z = 0x0000000000 and *Z += 5", operandBytes: 1 },
  { mnemonic: "INC", description: "Increment A: A = A + 1", operandBytes: 0 },
  { mnemonic: "INZ", description: "Increment zero-page byte: *Z = *Z + 1", operandBytes: 1 },
  { mnemonic: "INB", description: "Increment byte at addr: *addr = *addr + 1", operandBytes: 2 },
  { mnemonic: "INV", description: "Increment zero-page word: *V = *V + 0x0001", operandBytes: 1 },
  { mnemonic: "INW", description: "Increment word at addr: *addr = *addr + 0x0001", operandBytes: 2 },
  { mnemonic: "INQ", description: "Increment zero-page long: *Q = *Q + 0x00000001", operandBytes: 1 },
  { mnemonic: "DEC", description: "Decrement A: A = A - 1", operandBytes: 0 },
  { mnemonic: "DEZ", description: "Decrement *Z = *Z - 1", operandBytes: 1 },
  { mnemonic: "DEB", description: "Decrement byte: *addr = *addr - 1", operandBytes: 2 },
  { mnemonic: "DEV", description: "Decrement zero-page word: *V = *V - 0x0001", operandBytes: 1 },
  { mnemonic: "DEW", description: "Decrement word at addr: *addr = *addr - 0x0001", operandBytes: 2 },
  { mnemonic: "DEQ", description: "Decrement zero-page long: *Q = *Q - 0x00000001", operandBytes: 1 },
  { mnemonic: "ADI", description: "Add immediate to A: A = A + imm", operandBytes: 1 },
  { mnemonic: "ADZ", description: "Add zero-page byte to A: A = A + *Z", operandBytes: 1 },
  { mnemonic: "ADB", description: "Add byte at addr to A: A = A + *addr", operandBytes: 2 },
  { mnemonic: "ADT", description: "Add byte at rel zero-page addr to A: A = A + **Z", operandBytes: 1 },
  { mnemonic: "ADR", description: "Add byte at rel addr to A: A = A + **addr", operandBytes: 2 },
  { mnemonic: "AD.Z", description: "Add A to zero-page byte: *Z = *Z + A", operandBytes: 1 },
  { mnemonic: "AD.B", description: "Add A to byte at addr: *addr = *addr + A", operandBytes: 2 },
  { mnemonic: "AD.T", description: "Add A to rel zero-page address: **Z = **Z + A", operandBytes: 1 },
  { mnemonic: "AD.R", description: "Add A to rel address: **addr = **addr + A", operandBytes: 2 },
  { mnemonic: "ADV", description: "Add A to zero-page word: *V = *V + A", operandBytes: 1 },
  { mnemonic: "ADW", description: "Add A to word at addr: *addr = *addr + A", operandBytes: 2 },
  { mnemonic: "ADQ", description: "Add A to zero-page long: *Q = *Q + A", operandBytes: 1 },
  { mnemonic: "AIZ", description: "Add imm byte to zero-page byte: *Z = *Z + imm", operandBytes: 2 },
  { mnemonic: "AIB", description: "Add imm to byte at addr: *addr = *addr + imm", operandBytes: 3 },
  { mnemonic: "AIT", description: "Add imm to byte at rel Z addr: **Z = **Z + imm", operandBytes: 2 },
  { mnemonic: "AIR", description: "Add imm to byte at rel adr: *(*adr) = *(*adr) + imm", operandBytes: 3 },
  { mnemonic: "AIV", description: "Add imm byte to zero-page word: *V = *V + imm", operandBytes: 2 },
  { mnemonic: "AIW", description: "Add imm byte to abs word: *addr = *addr + imm", operandBytes: 3 },
  { mnemonic: "AIQ", description: "Add imm byte to zero-page long: *Q = *Q + imm", operandBytes: 2 },
  { mnemonic: "AZZ", description: "Add zero-page byte to zero-page byte: *Z2 = *Z2 + *Z1", operandBytes: 2 },
  { mnemonic: "AZT", description: "Add ZP byte to rel ZP address: **Z2 = **Z2 + *Z1", operandBytes: 2 },
  { mnemonic: "AZV", description: "Add zero-page byte to zero-page word: *V = *V + *Z", operandBytes: 2 },
  { mnemonic: "AZQ", description: "Add zero-page byte to zero-page long: *Q = *Q + *Z", operandBytes: 2 },
  { mnemonic: "ABB", description: "Add abs byte to byte: *adr2 = *adr2 + *adr1", operandBytes: 4 },
  { mnemonic: "ABW", description: "Add byte at ad1 to word at ad2: *ad2 = *ad2 + *ad1", operandBytes: 4 },
  { mnemonic: "ATZ", description: "Add byte at rel ZP addr to ZP byte: *Z2 = *Z2 + **Z1", operandBytes: 2 },
  { mnemonic: "ATT", description: "Add byte at rel ZP to rel ZP: **Z2 = **Z2 + **Z1", operandBytes: 2 },
  { mnemonic: "AVV", description: "Add zero-page word to zero-page word: *V2 = *V2 + *V1", operandBytes: 2 },
  { mnemonic: "SUI", description: "Sub immediate from A: A = A - imm", operandBytes: 1 },
  { mnemonic: "SUZ", description: "Sub zero-page byte from A: A = A - *Z", operandBytes: 1 },
  { mnemonic: "SUB", description: "Sub byte at addr from A: A = A - *addr", operandBytes: 2 },
  { mnemonic: "SUT", description: "Sub byte at rel zero-page addr from A: A = A - **Z", operandBytes: 1 },
  { mnemonic: "SUR", description: "Sub byte at rel addr from A: A = A - **addr", operandBytes: 2 },
  { mnemonic: "SU.Z", description: "Sub A from zero-page byte: *Z = *Z - A", operandBytes: 1 },
  { mnemonic: "SU.B", description: "Sub A from byte at addr: *addr = *addr - A", operandBytes: 2 },
  { mnemonic: "SU.T", description: "Sub A from rel zero-page address: **Z = **Z - A", operandBytes: 1 },
  { mnemonic: "SU.R", description: "Sub A from byte at rel addr: **addr = **addr - A", operandBytes: 2 },
  { mnemonic: "SUV", description: "Sub A from zero-page word: *v = *V - A", operandBytes: 1 },
  { mnemonic: "SUW", description: "Sub A from word at addr: *addr = *addr - A", operandBytes: 2 },
  { mnemonic: "SUQ", description: "Sub A from zero-page long: *Q = *Q - A", operandBytes: 1 },
  { mnemonic: "SIZ", description: "Sub immediate from zero-page byte: *Z = *Z - imm", operandBytes: 2 },
  { mnemonic: "SIB", description: "Sub imm from byte: *addr = *addr - imm", operandBytes: 3 },
  { mnemonic: "SIT", description: "Sub imm from byte at rel Z addr: **Z = **Z + imm", operandBytes: 2 },
  { mnemonic: "SIR", description: "Sub imm from byte at rel addr: *(*ad) = *(*ad) + imm", operandBytes: 3 },
  { mnemonic: "SIV", description: "Sub imm byte from zero-page word: *V = *V - imm", operandBytes: 2 },
  { mnemonic: "SIW", description: "Sub imm byte from abs word: *addr = *addr - imm", operandBytes: 3 },
  { mnemonic: "SIQ", description: "Sub imm byte from zero-page long Z: *Z = *Z - imm", operandBytes: 2 },
  { mnemonic: "SZZ", description: "Sub zero-page byte from Z byte: *Z2 = *Z2 - *Z1", operandBytes: 2 },
  { mnemonic: "SZT", description: "Sub ZP byte from rel ZP address: **Z2 = **Z2 + *Z1", operandBytes: 2 },
  { mnemonic: "SZV", description: "Sub zero-page byte from zero-page word: *V = *V - *Z", operandBytes: 2 },
  { mnemonic: "SZQ", description: "Sub zero-page byte from zero-page long: *Q = *Q - *Z", operandBytes: 2 },
  { mnemonic: "SBB", description: "Sub abs byte from byte: *adr2 = *adr2 - *adr1", operandBytes: 4 },
  { mnemonic: "SBW", description: "Sub abs byte from word at adr2: *adr2 = *adr2 - *adr1", operandBytes: 4 },
  { mnemonic: "STZ", description: "Sub byte at rel ZP addr from ZP byte: *Z2 = *Z2 - **Z1", operandBytes: 2 },
  { mnemonic: "STT", description: "Sub byte at rel ZP from rel ZP: **Z2 = **Z2 - **Z1", operandBytes: 2 },
  { mnemonic: "SVV", description: "Sub zero-page word from word: *V2 = *V2 - *V1", operandBytes: 2 },
  { mnemonic: "CPI", description: "Compare imm byte to A: eval A - imm", operandBytes: 1 },
  { mnemonic: "CPZ", description: "Compare byte in zero-page to A: eval A - *Z", operandBytes: 1 },
  { mnemonic: "CPB", description: "Compare byte at addr to A: eval A - *addr", operandBytes: 2 },
  { mnemonic: "CPT", description: "Compare byte at rel Z to A: eval A - **Z", operandBytes: 1 },
  { mnemonic: "CPR", description: "Compare byte at rel addr to A: eval A - **addr", operandBytes: 2 },
  { mnemonic: "CIZ", description: "Compare imm byte to zero-page byte: LDZ Z CPI ..", operandBytes: 2 },
  { mnemonic: "CIB", description: "Compare imm byte to byte at addr: LDB addr CPI ..", operandBytes: 3 },
  { mnemonic: "CIT", description: "Compare imm byte to byte at rel Z: LDT Z CPI ..", operandBytes: 2 },
  { mnemonic: "CIR", description: "Compare imm byte to byte at rel addr: LDR addr CPI ..", operandBytes: 3 },
  { mnemonic: "CIV", description: "Compare imm word to word in ZP: eval *V – imm", operandBytes: 3 },
  { mnemonic: "CIW", description: "Compare imm word to ZP word: eval *addr – imm", operandBytes: 4 },
  { mnemonic: "CZZ", description: "Compare byte in ZP to ZP byte: LDZ Z2 CPZ Z1", operandBytes: 2 },
  { mnemonic: "CZT", description: "Compare byte in ZP to rel ZP addr: LDT Z2 CPZ Z1", operandBytes: 2 },
  { mnemonic: "CBB", description: "Compare byte at adr1 to byte at adr2: LDB adr2 CPB adr1", operandBytes: 4 },
  { mnemonic: "CTZ", description: "Compare byte at rel ZP to ZP byte: LDZ Z2 CPT Z1", operandBytes: 2 },
  { mnemonic: "CTT", description: "Compare byte at rel ZP to rel ZP byte: LDT Z2 CPT Z1", operandBytes: 2 }, // spreadsheet sizes cell (2,2) contradicts the description/family (Z1,Z2 zero-page pointers, 1,1); see cpu.ts
  { mnemonic: "CVV", description: "Compare word in ZP to ZP word: eval *V2 - *V1", operandBytes: 2 },
  { mnemonic: "ACI", description: "Add imm byte to A with C: A = A + imm + C", operandBytes: 1 },
  { mnemonic: "ACZ", description: "Add byte in zero-page to A with C: A = A + *Z + C", operandBytes: 1 },
  { mnemonic: "AC.Z", description: "Add A to zero-page byte with C: *Z = *Z + A + C", operandBytes: 1 },
  { mnemonic: "SCI", description: "Sub imm byte from A with C: A = A - imm - 1 + C", operandBytes: 1 },
  { mnemonic: "SCZ", description: "Sub byte in ZP from A with C: A = A - *Z - 1 + C", operandBytes: 1 },
  { mnemonic: "SC.Z", description: "Sub A from zero-page byte with C: *Z = *Z - A - 1 + C", operandBytes: 1 },
  { mnemonic: "-", description: "internal use", operandBytes: 0 },
];
