/* --------------------------------------------------------------------------------------------
 * Copyright (c) 2024 TypeFox and others.
 * Licensed under the MIT License. See LICENSE in the package root for license information.
 * ------------------------------------------------------------------------------------------ */

import { IndentationAwareLexer, IndentationAwareTokenBuilder, type Module, inject } from "langium";
import {
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
  type PartialLangiumSharedServices,
  createDefaultModule,
  createDefaultSharedModule,
} from "langium/lsp";
import { MinminGeneratedSharedModule, MinminModelGeneratedModule } from "./generated/module.js";
import { MinminValidator, registerValidationChecks } from "./minmin-validator.js";
// import { MinminScopeComputation } from "./minmin-scope.js";
import { MinminConverter } from "./minmin-value.js";
import { MinminWorkspaceManager } from "./minmin-workspace.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
type MinminAddedServices = {
  validation: {
    MinminValidator: MinminValidator;
  };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MinminServices = LangiumServices & MinminAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
const MinminModule: Module<MinminServices, PartialLangiumServices & MinminAddedServices> = {
  validation: {
    MinminValidator: () => new MinminValidator(),
  },
  // references: {
  //   ScopeComputation: (services) => new MinminScopeComputation(services),
  // },
  parser: {
    // override the default value converter
    ValueConverter: (services) => new MinminConverter(),
    TokenBuilder: () => new IndentationAwareTokenBuilder(),
    Lexer: (services) => new IndentationAwareLexer(services),
  },
};

const MinminSharedModule: Module<LangiumSharedServices, PartialLangiumSharedServices> = {
  workspace: {
    WorkspaceManager: (services) => new MinminWorkspaceManager(services),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export async function createMinminServices(context: DefaultSharedModuleContext): Promise<{
  shared: LangiumSharedServices;
  minmin: MinminServices;
}> {
  const shared = inject(createDefaultSharedModule(context), MinminGeneratedSharedModule, MinminSharedModule);
  const minmin = inject(createDefaultModule({ shared }), MinminModelGeneratedModule, MinminModule);
  shared.ServiceRegistry.register(minmin);
  registerValidationChecks(minmin);
  if (context.connection === undefined) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    await shared.workspace.ConfigurationProvider.initialized({});
  }
  return { shared, minmin };
}
