/* --------------------------------------------------------------------------------------------
 * Copyright (c) 2024 TypeFox and others.
 * Licensed under the MIT License. See LICENSE in the package root for license information.
 * ------------------------------------------------------------------------------------------ */

import { type Module, inject } from "langium";
import {
  type DefaultSharedModuleContext,
  type LangiumServices,
  type LangiumSharedServices,
  type PartialLangiumServices,
  createDefaultModule,
  createDefaultSharedModule,
} from "langium/lsp";
import { MinasmGeneratedSharedModule, MinasmModelGeneratedModule } from "./generated/module.js";
import { MinasmValidator, registerValidationChecks } from "./minasm-validator.js";
import { MinasmScopeComputation } from "./minasm-scope.js";

/**
 * Declaration of custom services - add your own service classes here.
 */
type MinasmAddedServices = {
  validation: {
    MinasmValidator: MinasmValidator;
  };
};

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MinasmServices = LangiumServices & MinasmAddedServices;

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
const MinasmModule: Module<MinasmServices, PartialLangiumServices & MinasmAddedServices> = {
  validation: {
    MinasmValidator: () => new MinasmValidator(),
  },
  references: {
    ScopeComputation: (services) => new MinasmScopeComputation(services),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export async function createMinasmServices(context: DefaultSharedModuleContext): Promise<{
  shared: LangiumSharedServices;
  minasm: MinasmServices;
}> {
  console.log("createMinasmServices");
  const shared = inject(createDefaultSharedModule(context), MinasmGeneratedSharedModule);
  const minasm = inject(createDefaultModule({ shared }), MinasmModelGeneratedModule, MinasmModule);
  shared.ServiceRegistry.register(minasm);
  registerValidationChecks(minasm);
  if (context.connection === undefined) {
    // We don't run inside a language server
    // Therefore, initialize the configuration provider instantly
    await shared.workspace.ConfigurationProvider.initialized({});
  }
  return { shared, minasm };
}
